const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

function requireDemoPassword() {
  const password = process.env.DEMO_PASSWORD || process.env.SEED_DEMO_PASSWORD || process.env.DEMO_SEED_PASSWORD || '';
  if (password.length < 12 || password.length > 1024) throw new Error('DEMO_PASSWORD must contain 12-1024 characters');
  return password;
}

async function seed() {
  const client = await pool.connect();
  try {
    // Run schema
    const schema = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
    await client.query(schema);
    console.log('Schema created successfully');

    // Seed Users
    const hashedPassword = await bcrypt.hash(requireDemoPassword(), 10);
    await client.query(`
      INSERT INTO users (email, password, full_name, farm_name, location) VALUES
      ('admin@cropguard.com', '${hashedPassword}', 'John Farmer', 'Green Valley Farm', 'Iowa, USA'),
      ('jane@cropguard.com', '${hashedPassword}', 'Jane Smith', 'Sunrise Acres', 'California, USA'),
      ('raj@cropguard.com', '${hashedPassword}', 'Raj Patel', 'Patel Organics', 'Gujarat, India')
    `);
    console.log('Users seeded');

    // 1. Disease Detections (15 items)
    await client.query(`
      INSERT INTO disease_detections (user_id, crop_name, disease_name, confidence, severity, symptoms, affected_area, ai_diagnosis, status) VALUES
      (1, 'Tomato', 'Early Blight', 92.5, 'high', 'Dark concentric rings on lower leaves, yellowing around spots', 'North Field - Section A', 'Alternaria solani detected with high confidence. Fungal infection spreading from lower canopy. Immediate treatment recommended.', 'detected'),
      (1, 'Potato', 'Late Blight', 88.3, 'critical', 'Water-soaked lesions on leaves, white mold on undersides', 'East Plot - Row 12-18', 'Phytophthora infestans confirmed. Critical stage - can destroy entire crop within days if untreated.', 'treating'),
      (1, 'Wheat', 'Powdery Mildew', 95.1, 'medium', 'White powdery coating on leaf surfaces', 'West Field - Block B', 'Blumeria graminis detected. Moderate severity, primarily cosmetic at current stage but monitor closely.', 'detected'),
      (1, 'Rice', 'Bacterial Leaf Blight', 87.6, 'high', 'Yellow to white lesions along leaf veins', 'Paddy Field 3', 'Xanthomonas oryzae identified. High severity - affects grain filling. Copper-based treatment recommended.', 'treating'),
      (2, 'Corn', 'Gray Leaf Spot', 91.2, 'medium', 'Rectangular gray-brown lesions between veins', 'South Corridor - Field 2', 'Cercospora zeae-maydis confirmed. Moderate spread, fungicide application within 48hrs recommended.', 'detected'),
      (2, 'Soybean', 'Soybean Rust', 89.8, 'high', 'Tan to dark brown lesions on leaf undersides', 'Block C - Rows 1-20', 'Phakopsora pachyrhizi detected. Aggressive pathogen - preventive fungicide urgently needed.', 'treating'),
      (2, 'Apple', 'Fire Blight', 94.0, 'critical', 'Blackened shoots with shepherd crook shape, oozing cankers', 'Orchard Section 4', 'Erwinia amylovora confirmed. Critical - prune infected branches immediately, sterilize tools between cuts.', 'detected'),
      (2, 'Grape', 'Downy Mildew', 86.5, 'medium', 'Yellow oily spots on upper leaf surface, white down underneath', 'Vineyard Block A', 'Plasmopara viticola identified. Apply copper fungicide. Improve air circulation through canopy management.', 'resolved'),
      (3, 'Cotton', 'Verticillium Wilt', 90.7, 'high', 'Yellowing and wilting of leaves, vascular browning', 'Cotton Field - Zone 1', 'Verticillium dahliae detected. Soil-borne pathogen. Crop rotation essential for next season.', 'treating'),
      (3, 'Banana', 'Panama Disease', 93.4, 'critical', 'Yellowing of older leaves, pseudostem splitting', 'Plantation Sector B', 'Fusarium oxysporum f.sp. cubense TR4 detected. Quarantine affected area immediately.', 'detected'),
      (3, 'Mango', 'Anthracnose', 88.9, 'medium', 'Black sunken lesions on fruits, flower blight', 'Mango Grove - East', 'Colletotrichum gloeosporioides confirmed. Pre-harvest treatment critical for fruit quality.', 'treating'),
      (1, 'Strawberry', 'Botrytis Gray Mold', 91.6, 'high', 'Gray fuzzy mold on fruits, soft brown rot', 'Greenhouse 2 - Bay 5', 'Botrytis cinerea detected. Reduce humidity, improve ventilation, remove infected fruits.', 'detected'),
      (1, 'Citrus', 'Citrus Canker', 96.2, 'critical', 'Raised corky lesions on leaves and fruit', 'Orange Grove - Row 8-15', 'Xanthomonas citri confirmed. Regulatory concern - report to agricultural authority.', 'treating'),
      (2, 'Coffee', 'Coffee Leaf Rust', 87.3, 'high', 'Orange-yellow powdery spots on leaf undersides', 'Coffee Plantation - Sector 3', 'Hemileia vastatrix detected. Shade management and resistant variety replacement recommended.', 'detected'),
      (3, 'Cassava', 'Cassava Mosaic Disease', 93.8, 'high', 'Yellow-green mosaic pattern, leaf distortion', 'Cassava Plot 7', 'Cassava mosaic virus confirmed. Remove and destroy infected plants. Use virus-free planting material.', 'treating')
    `);
    console.log('Disease detections seeded');

    // 2. Pest Identifications (15 items)
    await client.query(`
      INSERT INTO pest_identifications (user_id, crop_name, pest_name, pest_type, confidence, damage_level, description, recommended_action, ai_analysis, status) VALUES
      (1, 'Tomato', 'Tomato Hornworm', 'Insect', 94.2, 'high', 'Large green caterpillar with white V-shaped marks', 'Hand-pick larvae, apply Bt (Bacillus thuringiensis)', 'Manduca quinquemaculata identified. Heavy defoliation observed. Biological control with parasitic wasps (Cotesia congregata) highly effective.', 'identified'),
      (1, 'Corn', 'Fall Armyworm', 'Insect', 91.8, 'critical', 'Brown-green larvae with inverted Y on head', 'Apply spinosad or chlorantraniliprole, scout at dusk', 'Spodoptera frugiperda confirmed. Invasive pest causing extensive damage to whorl. Immediate treatment critical.', 'treating'),
      (1, 'Rice', 'Brown Planthopper', 'Insect', 89.5, 'high', 'Small brown insects at plant base, honeydew secretion', 'Drain fields intermittently, apply imidacloprid', 'Nilaparvata lugens detected. Vector for rice grassy stunt virus. Integrated pest management approach recommended.', 'identified'),
      (2, 'Cotton', 'Cotton Bollworm', 'Insect', 93.1, 'critical', 'Green-brown larvae boring into cotton bolls', 'Pheromone traps, Bt cotton varieties, targeted insecticide', 'Helicoverpa armigera confirmed. Major economic pest - estimated 30% yield loss if untreated. IPM strategy essential.', 'treating'),
      (2, 'Wheat', 'Aphids', 'Insect', 96.3, 'medium', 'Small green-yellow insects clustered on stems', 'Introduce ladybugs, apply neem oil spray', 'Sitobion avenae colony detected. Moderate infestation. Natural enemies present - consider biological control first.', 'identified'),
      (2, 'Apple', 'Codling Moth', 'Insect', 90.7, 'high', 'Larvae tunneling into fruit, frass at entry holes', 'Pheromone traps, mating disruption, targeted spray at petal fall', 'Cydia pomonella confirmed. Timing of spray critical - target first generation larvae at 250 degree days.', 'treating'),
      (3, 'Soybean', 'Soybean Cyst Nematode', 'Nematode', 85.4, 'high', 'Stunted plants, yellowing, white cysts on roots', 'Rotate with non-host crops, use resistant varieties', 'Heterodera glycines detected. Soil population levels high. 2-year rotation minimum with corn recommended.', 'identified'),
      (3, 'Potato', 'Colorado Potato Beetle', 'Insect', 97.1, 'critical', 'Yellow-orange striped beetles, red larvae defoliating', 'Rotate insecticide classes, hand-pick adults, apply spinosad', 'Leptinotarsa decemlineata confirmed. Resistance to multiple insecticide classes noted. Rotation strategy critical.', 'treating'),
      (1, 'Grape', 'Grape Phylloxera', 'Insect', 88.9, 'high', 'Galls on roots and leaves, vine decline', 'Graft onto resistant rootstock, quarantine measures', 'Daktulosphaira vitifoliae detected. Root-feeding form most damaging. Resistant rootstock is primary management.', 'identified'),
      (1, 'Citrus', 'Asian Citrus Psyllid', 'Insect', 92.6, 'critical', 'Tiny mottled brown insects on new growth', 'Systemic insecticide, biological control with Tamarixia', 'Diaphorina citri confirmed. Vector of HLB/citrus greening. URGENT - report to agricultural authority.', 'treating'),
      (2, 'Mango', 'Mango Fruit Fly', 'Insect', 91.3, 'high', 'Maggots in ripe fruit, puncture marks', 'Protein bait traps, harvest early, cold treatment', 'Bactrocera dorsalis identified. High infestation pressure. Field sanitation critical - destroy fallen fruit.', 'identified'),
      (2, 'Coffee', 'Coffee Berry Borer', 'Insect', 94.5, 'critical', 'Small black beetle boring into coffee berries', 'Beauveria bassiana, strip picking, trap cropping', 'Hypothenemus hampei confirmed. Most damaging coffee pest globally. Biological control with Beauveria showing 70% efficacy.', 'treating'),
      (3, 'Banana', 'Banana Weevil', 'Insect', 87.8, 'high', 'Tunnels in corm, weakened plants toppling', 'Clean planting material, pseudostem traps, entomopathogenic fungi', 'Cosmopolites sordidus detected. Corm damage exceeds 40%. Pheromone mass trapping recommended.', 'identified'),
      (3, 'Cassava', 'Cassava Mealybug', 'Insect', 90.2, 'medium', 'White waxy insects on growing tips, stunted growth', 'Release Anagyrus lopezi parasitoid, avoid over-fertilization', 'Phenacoccus manihoti identified. Classical biological control with parasitoid wasps most effective long-term solution.', 'treating'),
      (1, 'Strawberry', 'Spider Mites', 'Arachnid', 93.7, 'medium', 'Fine webbing on undersides, stippled yellowing leaves', 'Predatory mites (Phytoseiulus persimilis), miticide if severe', 'Tetranychus urticae colony detected. Hot dry conditions favor outbreaks. Augmentative biological control recommended.', 'identified')
    `);
    console.log('Pest identifications seeded');

    // 3. Crop Health Monitoring (15 items)
    await client.query(`
      INSERT INTO crop_health (user_id, crop_name, field_name, health_score, growth_stage, ndvi_value, chlorophyll_level, water_stress, notes, ai_assessment) VALUES
      (1, 'Tomato', 'North Field A', 85, 'Flowering', 0.72, 'optimal', 'none', 'Plants showing vigorous growth, good fruit set', 'Overall crop health excellent. NDVI indicates strong canopy. Monitor for blossom end rot with current watering schedule.'),
      (1, 'Wheat', 'West Block B', 62, 'Grain Filling', 0.55, 'below_normal', 'moderate', 'Some yellowing in lower canopy, uneven heading', 'Moderate stress detected. Chlorophyll deficit suggests nitrogen deficiency. Foliar application of urea recommended within 5 days.'),
      (1, 'Corn', 'South Field 1', 91, 'Vegetative V8', 0.81, 'optimal', 'none', 'Excellent stand establishment, uniform growth', 'Premium health status. Growth rate on track for target yield of 200 bu/acre. Continue current management program.'),
      (1, 'Rice', 'Paddy Field 2', 74, 'Tillering', 0.64, 'normal', 'mild', 'Good tiller count but some iron deficiency spots', 'Minor nutritional stress. Iron chlorosis in alkaline patches. Apply ferrous sulfate to affected areas. Drain management good.'),
      (2, 'Soybean', 'Block C', 78, 'Pod Development', 0.68, 'normal', 'mild', 'Pod fill progressing well despite heat stress last week', 'Recovery from heat stress evident. Pod retention at 85%. Maintain adequate irrigation through seed fill stage.'),
      (2, 'Apple', 'Orchard East', 88, 'Fruit Development', 0.75, 'optimal', 'none', 'Good fruit size, thinning was effective', 'Excellent fruit development trajectory. Calcium spray recommended to prevent bitter pit. Harvest timing in 45 days optimal.'),
      (2, 'Grape', 'Vineyard A', 71, 'Veraison', 0.59, 'below_normal', 'moderate', 'Uneven ripening, some leaf scorch', 'Water stress during veraison may concentrate sugars but risk quality. Deficit irrigation adjustment needed. Brix monitoring advised.'),
      (2, 'Cotton', 'Cotton Zone 2', 83, 'Boll Opening', 0.71, 'normal', 'none', 'Good boll load, 3.2 bolls per plant average', 'Strong yield potential. First position bolls well-developed. Defoliation timing recommended at 60% open bolls.'),
      (3, 'Coffee', 'Plantation Sector 1', 79, 'Cherry Development', 0.66, 'normal', 'mild', 'Cherry sizing good, shade management adequate', 'Healthy cherry development. Mild water stress acceptable for flavor concentration. Maintain shade at 40-50% canopy cover.'),
      (3, 'Banana', 'Plantation B', 68, 'Bunch Emergence', 0.58, 'below_normal', 'moderate', 'Smaller than expected bunch size, leaf damage', 'Stress indicators present. Potassium supplementation critical for bunch weight. Leaf area reduction affecting photosynthate supply.'),
      (3, 'Mango', 'Grove East', 92, 'Fruit Maturation', 0.79, 'optimal', 'none', 'Heavy fruit set, excellent size', 'Outstanding crop condition. Fruit calcium levels adequate. Pre-harvest interval for any sprays must be observed. Harvest in 20 days.'),
      (1, 'Potato', 'East Plot', 56, 'Tuber Bulking', 0.48, 'low', 'high', 'Wilting observed, tuber size below target', 'Significant stress detected. NDVI decline of 15% in 10 days. Possible Verticillium wilt or severe water deficit. Immediate investigation required.'),
      (1, 'Strawberry', 'Greenhouse 1', 87, 'Fruiting', 0.74, 'optimal', 'none', 'Continuous harvest, 340g/plant average', 'Excellent production. Runner removal keeping energy in fruit production. Botrytis risk elevated - maintain ventilation protocol.'),
      (2, 'Citrus', 'Orange Grove', 76, 'Fruit Sizing', 0.63, 'normal', 'mild', 'Fruit count good but sizing slightly behind', 'Mid-season assessment positive. Increase irrigation by 15% for optimal fruit sizing. Foliar potassium spray recommended.'),
      (3, 'Cassava', 'Plot 5', 82, 'Root Bulking', 0.70, 'normal', 'none', 'Vigorous canopy, root development on track', 'Healthy root development phase. Starch accumulation progressing well. Harvest window optimal in 60-90 days for maximum yield.')
    `);
    console.log('Crop health monitoring seeded');

    // 4. Treatment Recommendations (15 items)
    await client.query(`
      INSERT INTO treatment_recommendations (user_id, disease_or_pest, crop_name, treatment_type, treatment_name, dosage, application_method, frequency, precautions, organic_alternative, effectiveness_rating, ai_recommendation, status) VALUES
      (1, 'Early Blight', 'Tomato', 'Fungicide', 'Chlorothalonil', '2.25 pt/acre', 'Foliar spray with full coverage', 'Every 7-10 days', 'REI 12 hours, PHI 0 days for tomatoes', 'Copper hydroxide + Bacillus subtilis biofungicide', 85, 'Start applications preventively. Alternate with mancozeb to prevent resistance. Lower leaf removal reduces inoculum. Mulching prevents soil splash.', 'active'),
      (1, 'Late Blight', 'Potato', 'Fungicide', 'Mefenoxam + Mancozeb', '2.5 lb/acre', 'Broadcast spray, ensure lower canopy coverage', 'Every 5-7 days during active disease', 'Do not apply more than 4 times per season', 'Copper octanoate spray + resistant variety selection', 92, 'URGENT: Late blight moves fast. First application within 24hrs. Monitor weather for >90% humidity events. Consider vine kill if >25% infected.', 'active'),
      (1, 'Tomato Hornworm', 'Tomato', 'Biological', 'Bacillus thuringiensis var. kurstaki', '0.5-1.5 lb/acre', 'Spray on foliage when larvae are small', 'As needed when larvae detected', 'Apply in evening, UV breaks down Bt', 'Hand-picking + parasitic wasp conservation', 78, 'Bt most effective on young larvae. Scout twice weekly. Parasitic wasps (Cotesia congregata) provide natural control - avoid broad-spectrum insecticides.', 'active'),
      (2, 'Fall Armyworm', 'Corn', 'Insecticide', 'Chlorantraniliprole', '5 fl oz/acre', 'Directed spray into whorl', 'Single application at threshold', 'Low toxicity to beneficials, 1-day PHI', 'Spinosad + Trichogramma egg parasitoids', 88, 'Apply when larvae are in early instars (< 0.5 inch). Evening applications more effective. Bt corn provides partial resistance. Scout field edges first.', 'active'),
      (2, 'Aphids', 'Wheat', 'Biological', 'Ladybug Release', '1500 per acre', 'Release at dusk near aphid colonies', 'Single release, monitor for 2 weeks', 'Pre-water field before release, avoid insecticides', 'Neem oil spray + companion planting with dill', 72, 'Natural enemy complex often sufficient. Economic threshold: 12-15 aphids per tiller. Release ladybugs + lacewings for best results. Neem oil as supplement.', 'active'),
      (2, 'Codling Moth', 'Apple', 'Pheromone', 'Mating Disruption Dispensers', '200 dispensers/acre', 'Hang in upper third of canopy', 'Once per season, replace after 120 days', 'Most effective in blocks >5 acres, supplement edges', 'Granulosis virus (CpGV) + nematode soil drench', 90, 'Deploy dispensers before first flight. Supplement with 1-2 targeted sprays at peak flight. Monitor with pheromone traps. Fruit bagging for small orchards.', 'active'),
      (3, 'Soybean Cyst Nematode', 'Soybean', 'Cultural', 'Crop Rotation + Resistant Varieties', 'N/A', 'Plant resistant variety after 2-year corn rotation', 'Annual rotation planning', 'Verify SCN race before selecting resistant variety', 'Mustard biofumigation + Paecilomyces biocontrol', 82, 'Soil test for SCN egg counts. PI 88788 resistance source most common but declining. Diversify resistance sources. Biofumigation with mustard crops promising.', 'active'),
      (1, 'Powdery Mildew', 'Wheat', 'Fungicide', 'Propiconazole', '4 fl oz/acre', 'Foliar spray at flag leaf emergence', 'Preventive: once at GS 37-39', 'Do not apply after heading for grain wheat', 'Potassium bicarbonate + sulfur dust', 86, 'Timing is critical - protect flag leaf. Varietal resistance is primary defense. In organic systems, sulfur dust at 20 lb/acre provides good control.', 'active'),
      (1, 'Bacterial Leaf Blight', 'Rice', 'Bactericide', 'Copper Hydroxide', '1.5 lb/acre', 'Foliar spray with sticker-spreader', 'Every 10-14 days during monsoon', 'May cause phytotoxicity in high temps, test first', 'Streptomycin sulfate + resistant varieties', 70, 'Copper provides suppression, not cure. Drain fields to reduce humidity. Plant resistant varieties (IRBB lines). Avoid excess nitrogen which increases susceptibility.', 'active'),
      (2, 'Cotton Bollworm', 'Cotton', 'IPM', 'Integrated Pest Management Program', 'Variable', 'Combination of tactics: scout, trap, spray threshold-based', 'Continuous monitoring, spray as needed', 'Rotate insecticide modes of action', 'Bt cotton + Trichogramma releases + NPV virus', 91, 'Economic threshold: 8% damaged squares or 5% damaged bolls. Bt cotton provides baseline control. Supplement with targeted sprays only when threshold exceeded.', 'active'),
      (2, 'Downy Mildew', 'Grape', 'Fungicide', 'Metalaxyl + Copper', '3 lb/acre', 'Thorough canopy spray both sides of row', 'Every 14 days preventive, 7 days curative', 'Metalaxyl resistance possible, alternate chemistry', 'Bordeaux mixture + canopy management', 84, 'Open canopy through shoot positioning and leaf removal for air circulation. Start sprays at 10-inch shoot growth. Organic: Bordeaux mixture has centuries of proven efficacy.', 'active'),
      (3, 'Panama Disease', 'Banana', 'Cultural', 'Biosecurity + Resistant Cultivars', 'N/A', 'Quarantine, clean planting material, resistant varieties', 'Ongoing biosecurity protocol', 'TR4 strain has NO chemical cure - prevention only', 'Trichoderma soil amendments + FHIA resistant varieties', 75, 'NO CHEMICAL CURE for Fusarium TR4. Strict biosecurity: boot wash stations, tool sterilization, vehicle wash. Plant GCTCV-219 or FHIA-18 resistant varieties.', 'active'),
      (3, 'Coffee Leaf Rust', 'Coffee', 'Fungicide', 'Cyproconazole + Azoxystrobin', '0.8 L/ha', 'Spray covering both leaf surfaces', 'Every 30-45 days during rainy season', 'Maximum 3 applications per season', 'Bordeaux mixture + shade management + resistant varieties', 83, 'Shade-grown coffee has 20-30% less rust. Prune for air circulation. Long-term: transition to F1 hybrids (Centroamericano, Starmaya) with durable resistance.', 'active'),
      (1, 'Botrytis Gray Mold', 'Strawberry', 'Fungicide', 'Fenhexamid', '1.5 lb/acre', 'Spray at 10% bloom, repeat at full bloom', '2-3 applications during bloom period', 'Alternate with different FRAC groups', 'Bacillus amyloliquefaciens + UV-C treatment', 87, 'Key timing: bloom period is critical infection window. Reduce humidity below 80%. Drip irrigation preferred over overhead. Remove infected fruit promptly.', 'active'),
      (3, 'Citrus Canker', 'Citrus', 'Bactericide', 'Copper Hydroxide + Mancozeb', '6 lb/acre Cu + 3 lb/acre Mn', 'Thorough coverage spray including fruit', 'Every 21 days, more frequent in rainy season', 'Windbreaks reduce spread, avoid working in wet conditions', 'Fixed copper formulations + windbreak establishment', 68, 'Regulatory pest in many regions - check local requirements. Windbreaks reduce bacterial spread by 40%. Resistant varieties (some Satsuma mandarins) available.', 'active')
    `);
    console.log('Treatment recommendations seeded');

    // 5. Weather Risk Assessment (15 items)
    await client.query(`
      INSERT INTO weather_risks (user_id, location, risk_type, risk_level, temperature, humidity, rainfall, wind_speed, forecast_summary, disease_risk_factors, ai_risk_analysis) VALUES
      (1, 'Iowa, USA', 'Fungal Disease Outbreak', 'high', 28.5, 92.0, 45.0, 8.5, '5-day warm humid period with scattered thunderstorms', 'Extended leaf wetness >12hrs, optimal temperature for Cercospora', 'HIGH RISK: Gray leaf spot and northern corn leaf blight conditions optimal. Preventive fungicide recommended for corn. Scout daily for symptoms.'),
      (1, 'Iowa, USA', 'Frost Damage', 'medium', 2.1, 65.0, 0.0, 12.3, 'Cold front approaching, overnight lows near freezing', 'Late frost risk for emerged crops, frost heaving in root crops', 'Frost advisory for next 48hrs. Cover tender transplants. Delay planting warm-season crops. Potato and strawberry fields most vulnerable.'),
      (1, 'Iowa, USA', 'Drought Stress', 'low', 31.2, 45.0, 2.0, 15.6, 'Dry conditions expected to continue for 10 days', 'Reduced plant defense mechanisms, spider mite population increase', 'Current soil moisture adequate. If dry period extends beyond 14 days, initiate supplemental irrigation. Monitor for mite buildup.'),
      (2, 'California, USA', 'Heat Wave', 'critical', 42.8, 18.0, 0.0, 5.2, 'Extreme heat event, 4+ days above 40°C', 'Sunscald on fruits, pollen sterility, rapid water loss', 'CRITICAL: Deploy shade cloth on sensitive crops. Increase irrigation frequency. Harvest ripe fruit immediately. Night cooling recommended for greenhouses.'),
      (2, 'California, USA', 'Wildfire Smoke', 'high', 35.1, 30.0, 0.0, 3.8, 'Smoke advisory from regional wildfires, poor air quality', 'Reduced photosynthesis, smoke taint in wine grapes', 'Smoke exposure >72hrs impacts grape quality. Consider early harvest for wine grapes. Wash fruit surfaces. Monitor PAR levels for greenhouse crops.'),
      (2, 'California, USA', 'Flooding', 'medium', 18.5, 88.0, 85.0, 22.4, 'Atmospheric river event bringing heavy rainfall', 'Root rot, soil erosion, nutrient leaching, bacterial spread', 'Ensure drainage systems clear. Delay fertilizer applications. Post-flood copper spray recommended. Monitor for Phytophthora root rot 7-14 days after event.'),
      (3, 'Gujarat, India', 'Monsoon Disease Risk', 'critical', 32.0, 95.0, 120.0, 18.0, 'Heavy monsoon rainfall expected for next week', 'Ideal conditions for downy mildew, bacterial blight, anthracnose', 'CRITICAL: Pre-monsoon fungicide application urgently needed. Ensure field drainage. Bacterial diseases in rice paddies will accelerate. Harvest mature crops now.'),
      (3, 'Gujarat, India', 'Pest Migration', 'high', 29.5, 78.0, 35.0, 25.6, 'Strong SW winds coinciding with locust breeding season', 'Desert locust swarm potential, armyworm migration corridor', 'Locust early warning active. Coordinate with district pest surveillance. Prepare emergency spray equipment. Community alert system activated.'),
      (3, 'Gujarat, India', 'Heat Stress', 'high', 44.2, 25.0, 0.0, 8.9, 'Pre-monsoon heat wave, extreme temperatures', 'Flower drop in pulses, reduced pollination, heat stroke in workers', 'Worker safety: restrict field work 11am-4pm. Mulch to reduce soil temperature. Foliar spray with kaolin clay for heat reflection.'),
      (1, 'Iowa, USA', 'Hail Damage', 'medium', 24.8, 75.0, 30.0, 35.2, 'Severe thunderstorm warning with large hail possible', 'Physical crop damage, wound entry for pathogens', 'Deploy hail nets if available. Post-hail: apply copper fungicide within 24hrs to prevent bacterial infection through wounds. Document damage for insurance.'),
      (2, 'California, USA', 'Wind Damage', 'high', 22.0, 40.0, 5.0, 65.0, 'Santa Ana wind event, gusts to 100 km/h expected', 'Tree breakage, fruit drop, desiccation, fire risk', 'Stake young trees. Harvest mature fruit before wind event. Irrigate to reduce desiccation stress. Trellised crops: check wire tension and post anchoring.'),
      (2, 'California, USA', 'UV Stress', 'medium', 36.5, 28.0, 0.0, 8.0, 'Clear skies with elevated UV index >11', 'Sunscald on thin-skinned fruits, leaf burn on transplants', 'Apply kaolin clay (Surround WP) to sun-exposed fruits. Shade cloth for nursery transplants. Avoid midday foliar sprays that can cause lens burn.'),
      (3, 'Gujarat, India', 'Cyclone Warning', 'critical', 30.0, 90.0, 200.0, 85.0, 'Tropical cyclone approaching coast within 72 hours', 'Total crop destruction possible, flooding, wind damage', 'EMERGENCY: Harvest all possible crops immediately. Secure structures and equipment. Prepare drainage for flooding. Post-cyclone disease management plan needed.'),
      (1, 'Iowa, USA', 'Early Season Cold', 'medium', 8.5, 70.0, 15.0, 10.2, 'Cool wet spring delaying planting window', 'Seedling diseases (Pythium, Fusarium), slow emergence', 'Delay corn planting until soil temp >10°C at 4-inch depth. Use seed treatments. Consider switching to shorter-season varieties if planting delayed >2 weeks.'),
      (3, 'Gujarat, India', 'Fog Advisory', 'low', 12.0, 98.0, 0.0, 2.0, 'Dense fog expected for next 3 mornings', 'Extended leaf wetness promoting fungal diseases', 'Fog creates leaf wetness without rain - disease risk often underestimated. Preventive fungicide spray before fog events. Good air circulation critical.')
    `);
    console.log('Weather risks seeded');

    // 6. Soil Analysis (15 items)
    await client.query(`
      INSERT INTO soil_analyses (user_id, field_name, soil_type, ph_level, nitrogen_level, phosphorus_level, potassium_level, organic_matter, moisture_content, recommendations, ai_analysis) VALUES
      (1, 'North Field A', 'Loamy Clay', 6.80, 45.2, 32.1, 180.5, 3.8, 28.5, 'Maintain current pH. Add nitrogen for heavy feeders.', 'Excellent soil health profile. Organic matter above regional average. CEC adequate for nutrient retention. Recommend cover crop in off-season to maintain structure.'),
      (1, 'West Block B', 'Sandy Loam', 5.90, 28.4, 18.7, 120.3, 2.1, 15.2, 'Lime needed to raise pH. Increase organic matter.', 'Low pH limiting nutrient availability, especially phosphorus. Apply 2 tons/acre agricultural lime. Sandy texture requires split nitrogen applications to reduce leaching.'),
      (1, 'East Plot', 'Clay', 7.40, 52.8, 45.6, 220.1, 4.5, 35.8, 'Slightly alkaline - add sulfur. Good fertility overall.', 'High clay content provides excellent nutrient retention but drainage concerns. pH slightly high - iron and manganese may be limited. Gypsum application improves structure.'),
      (1, 'South Field 1', 'Silt Loam', 6.50, 38.9, 28.3, 165.7, 3.2, 24.6, 'Optimal pH. Maintain phosphorus levels.', 'Prime agricultural soil. Well-balanced nutrient profile. Continue current fertilization program. Monitor potassium draw-down with heavy corn production.'),
      (2, 'Block C', 'Loam', 6.70, 42.1, 35.2, 195.4, 3.5, 26.3, 'Well-balanced. Continue current program.', 'Textbook soil health indicators. Biological activity indicators strong. Mycorrhizal colonization likely high. Avoid excessive tillage to preserve soil structure.'),
      (2, 'Orchard East', 'Sandy Clay Loam', 6.20, 35.6, 55.8, 210.8, 2.8, 20.1, 'Increase nitrogen. Phosphorus high - reduce applications.', 'Phosphorus accumulation from years of fertilization - cease P applications for 2 years. Nitrogen fixation with cover crops recommended. Mulch ring management important.'),
      (2, 'Vineyard A', 'Gravelly Loam', 7.10, 22.5, 15.4, 140.2, 1.9, 12.8, 'Low fertility by design for quality wine grapes.', 'Deliberately lean soil for wine grape quality. Avoid over-fertilization which reduces wine quality. Moderate water stress acceptable. Cover crop for erosion control only.'),
      (2, 'Cotton Zone 2', 'Heavy Clay', 7.80, 48.3, 38.9, 250.6, 3.0, 40.2, 'Apply gypsum for calcium and structure. Reduce pH.', 'Sodic tendencies developing. Gypsum at 3 tons/acre recommended. Waterlogging risk in heavy rain. Deep ripping may improve root penetration. Monitor sodium levels.'),
      (3, 'Plantation Sector 1', 'Laterite', 5.40, 18.9, 12.3, 85.6, 1.5, 22.4, 'Heavy liming needed. Build organic matter urgently.', 'Acid laterite soil typical of tropical regions. Aluminum toxicity risk at this pH. Apply dolomitic lime 4 tons/acre. Organic matter building with mulch critical for CEC.'),
      (3, 'Plantation B', 'Volcanic Loam', 6.00, 55.4, 48.2, 175.3, 5.2, 30.5, 'Excellent natural fertility. Minor pH adjustment needed.', 'Exceptional volcanic soil with high natural fertility. Allophanic clays provide excellent nutrient retention. Slight pH increase with light liming would optimize phosphorus availability.'),
      (3, 'Grove East', 'Red Earth', 6.30, 30.2, 22.8, 145.9, 2.4, 18.7, 'Increase organic matter. Balanced fertilization needed.', 'Typical tropical red earth with good iron content. Organic matter building priority. Compost applications at 5 tons/acre/year recommended. Mulching conserves moisture.'),
      (1, 'Greenhouse 1', 'Potting Mix', 6.40, 65.3, 58.7, 280.4, 8.5, 45.2, 'EC running high. Flush with clear water.', 'Soilless media showing salt accumulation. Leaching fraction should be 20-30%. Reduce fertilizer concentration by 25%. pH within acceptable range for most greenhouse crops.'),
      (1, 'Paddy Field 2', 'Alluvial Clay', 6.90, 40.1, 30.5, 160.8, 3.6, 55.3, 'Good paddy soil. Maintain puddling for water retention.', 'Typical paddy soil in good condition. Anaerobic conditions during flooding release iron and manganese. Zinc supplementation recommended as flooding reduces Zn availability.'),
      (2, 'Orange Grove', 'Calcareous Loam', 7.90, 32.8, 25.6, 190.2, 2.6, 19.8, 'Iron chlorosis risk. Apply chelated iron.', 'High calcium carbonate content (est. 12%) locking out micronutrients. EDDHA iron chelate required - standard EDTA ineffective above pH 7.5. Acidifying fertilizers recommended.'),
      (3, 'Plot 5', 'Sandy Loam', 6.10, 25.6, 20.1, 110.5, 2.0, 14.5, 'Build fertility with compost. Increase water retention.', 'Light-textured soil suitable for cassava but nutrient leaching concern. Biochar application at 2 tons/acre would significantly improve water and nutrient retention. Cover cropping essential.')
    `);
    console.log('Soil analyses seeded');

    // 7. Crop Calendar (15 items)
    await client.query(`
      INSERT INTO crop_calendar (user_id, crop_name, activity, scheduled_date, season, priority, notes, status, ai_suggestion) VALUES
      (1, 'Corn', 'Spring Planting', '2026-04-15', 'Spring', 'critical', 'Soil temp must be >10°C at 4-inch depth', 'planned', 'Optimal window: Apr 10-25. Check 10-day forecast. Treat seed with fungicide+insecticide for cold soil. Population: 34,000 seeds/acre.'),
      (1, 'Tomato', 'Transplant to Field', '2026-05-01', 'Spring', 'high', 'After last frost date. Harden off seedlings 7 days prior', 'planned', 'Wait until soil temp >15°C. Install drip irrigation before transplanting. Stake or cage at planting. Apply starter fertilizer in transplant hole.'),
      (1, 'Wheat', 'Harvest', '2026-07-10', 'Summer', 'critical', 'Monitor grain moisture - target 13-14%', 'planned', 'Test moisture daily starting July 1. Combine when grain moisture <14%. Avoid harvest losses from over-ripe shattering. Schedule truck logistics.'),
      (1, 'Potato', 'Hilling', '2026-05-20', 'Spring', 'high', 'Hill when plants are 8-10 inches tall', 'planned', 'Hill to 6 inches covering lower stems. This prevents green tubers and increases yield. Second hilling 2 weeks later if vigorous growth.'),
      (2, 'Apple', 'Dormant Spray', '2026-02-15', 'Winter', 'high', 'Apply before bud break, copper + oil', 'completed', 'Copper hydroxide at 4 lb/acre + dormant oil at 2%. Target: overwintering fungal inoculum and scale insects. Apply on calm day >4°C.'),
      (2, 'Grape', 'Pruning', '2026-03-01', 'Spring', 'critical', 'Prune to 2-bud spurs for quality wine', 'completed', 'Balance crop load: 30 buds per vine for quality. Sterilize pruning shears between blocks. Leave 1-2 extra buds as frost insurance. Paint large wounds.'),
      (2, 'Soybean', 'Planting', '2026-05-10', 'Spring', 'critical', 'Inoculate with Bradyrhizobium if first-time soybean field', 'planned', 'Row spacing 15-inch for maximum yield. Inoculant critical for new fields. Plant 140,000 seeds/acre. Check seed germination before planting.'),
      (2, 'Cotton', 'First Irrigation', '2026-06-01', 'Summer', 'high', 'Apply 2 inches when soil moisture deficit reaches 50%', 'planned', 'Install soil moisture sensors. First irrigation timing critical for root development. Avoid waterlogging. Furrow irrigation preferred for cotton.'),
      (3, 'Coffee', 'Pruning and Training', '2026-01-15', 'Winter', 'medium', 'Remove suckers, shape productive branches', 'completed', 'Maintain single-stem system. Remove all suckers below first lateral. Tip productive branches to stimulate laterals. Target 60-80 productive nodes per tree.'),
      (3, 'Banana', 'Desuckering', '2026-04-01', 'Spring', 'high', 'Keep mother + follower + peeper only', 'planned', 'Select sword suckers, not water suckers. Cut at ground level with sharp machete. Leave the most vigorous successor. Apply herbicide to unwanted sucker stumps.'),
      (3, 'Mango', 'Flower Induction', '2026-10-15', 'Fall', 'critical', 'Apply potassium nitrate spray if no natural flowering', 'planned', 'KNO3 at 2% concentration spray. Requires prior water stress period of 2-3 months. Target mature terminal shoots. Expected flowering 2-3 weeks after spray.'),
      (1, 'Strawberry', 'Runner Planting', '2026-08-15', 'Summer', 'high', 'Plant runners from certified disease-free stock', 'planned', 'Select runners with good root development. Plant crown at soil level - not too deep. Irrigate immediately. Pinch first flowers to build plant strength.'),
      (1, 'Rice', 'Transplanting', '2026-06-15', 'Summer', 'critical', '25-day old seedlings, 2-3 seedlings per hill', 'planned', 'Puddle field day before transplanting. 20x20 cm spacing for SRI method. Keep 2-3 cm water depth after transplanting. Apply basal fertilizer before puddling.'),
      (2, 'Citrus', 'Fertilizer Application', '2026-03-15', 'Spring', 'high', 'First of 3 split applications for the year', 'planned', 'Apply 1/3 annual N requirement. Spread under canopy drip line, not against trunk. Irrigate after application. Include micronutrients Zn, Mn, Fe in spring application.'),
      (3, 'Cassava', 'Planting Stakes', '2026-04-20', 'Spring', 'critical', 'Use mature stem cuttings 20-25 cm long', 'planned', 'Select stems 8-12 months old. Cut with sharp tool, not machete chop. Plant at 45-degree angle or horizontal. Spacing 1m x 1m. Apply NPK 15-15-15 at planting.')
    `);
    console.log('Crop calendar seeded');

    // 8. Pest Alerts (15 items)
    await client.query(`
      INSERT INTO pest_alerts (user_id, alert_title, pest_name, region, severity, affected_crops, description, prevention_tips, ai_alert_analysis, is_active) VALUES
      (1, 'Fall Armyworm Migration Detected', 'Fall Armyworm', 'Midwest USA', 'critical', 'Corn, Sorghum, Rice', 'Large-scale migration from southern states confirmed by trap networks', 'Scout fields weekly, deploy pheromone traps, prepare spray equipment', 'Migration pattern consistent with warm jet stream. Expected arrival in 7-10 days. Historical damage: 20-40% yield loss. Bt corn provides partial resistance but scout for breakthrough.', true),
      (1, 'Soybean Aphid Threshold Alert', 'Soybean Aphid', 'Iowa, USA', 'high', 'Soybean', 'Aphid populations reaching economic threshold in regional monitoring', 'Scout field edges, natural enemies may provide control', 'Regional populations building to 250+ per plant threshold. Check for lady beetle and lacewing activity before spraying. Winged forms indicate migration pressure.', true),
      (2, 'Citrus Greening Quarantine Extended', 'Asian Citrus Psyllid', 'Southern California', 'critical', 'Citrus (all varieties)', 'New HLB-positive trees found, quarantine zone expanded 5 miles', 'Inspect new growth for psyllids, systemic treatment mandatory', 'Quarantine expansion significant. All citrus within zone must be treated. Report symptomatic trees immediately. No movement of citrus plant material from zone.', true),
      (2, 'Spotted Wing Drosophila Season Start', 'Spotted Wing Drosophila', 'California, USA', 'high', 'Strawberry, Blueberry, Cherry, Grape', 'First adult catches in monitoring traps, season officially started', 'Install traps, begin spray program, harvest ripe fruit promptly', 'Early season detection 10 days ahead of normal. Warm winter contributed to larger overwintering population. Spinosad + good sanitation is primary defense.', true),
      (3, 'Desert Locust Swarm Warning', 'Desert Locust', 'Western India', 'critical', 'All crops', 'Breeding swarms reported in Rajasthan, moving southeast', 'Community alert networks, prepare emergency spray teams', 'EMERGENCY ALERT: Swarm estimated at 40 million+ insects. Can consume 80,000 tonnes of food/day. Coordinate with district agriculture office. Evening spraying most effective.', true),
      (3, 'Pink Bollworm Resistance Alert', 'Pink Bollworm', 'Gujarat, India', 'high', 'Cotton', 'Field-evolved resistance to Bt cotton confirmed in multiple districts', 'Refuge planting critical, rotate Bt events, scout regularly', 'Resistance to Cry1Ac confirmed. Dual-gene Bt varieties still effective but monitor closely. Refuge compliance essential. Mating disruption as supplementary tactic.', true),
      (1, 'Corn Rootworm Beetle Emergence', 'Western Corn Rootworm', 'Corn Belt, USA', 'medium', 'Corn', 'Beetle emergence beginning across the region', 'Crop rotation, soil-applied insecticide for continuous corn', 'Rotation-resistant variant present in some areas. Sticky trap counts indicate moderate pressure. Continuous corn fields: consider soil insecticide or Bt rootworm hybrids.', true),
      (1, 'Late Blight Alert', 'Phytophthora infestans', 'Northeast USA', 'critical', 'Potato, Tomato', 'US-23 genotype confirmed in regional samples, highly aggressive', 'Begin preventive fungicide immediately, destroy cull piles', 'US-23 genotype is mefenoxam-sensitive, which is good news. But extremely aggressive. 5-7 day spray intervals required. Check DSV (disease severity values) daily.', true),
      (2, 'Navel Orangeworm Season', 'Navel Orangeworm', 'Central Valley, CA', 'high', 'Almond, Pistachio, Walnut', 'First generation flight detected, sanitation deadline approaching', 'Remove mummy nuts before April 1, deploy egg traps', 'Sanitation is THE most effective tactic. Remove 100% of mummy nuts. Mating disruption effective in well-managed orchards. Harvest timing critical for almond.', true),
      (2, 'Glassy-Winged Sharpshooter Finds', 'Glassy-Winged Sharpshooter', 'Napa Valley, CA', 'high', 'Grape', 'Vector of Pierces Disease detected in adjacent county', 'Inspect shipments, treat with systemic insecticide', 'Vector detection triggers mandatory treatment zone. Pierce Disease kills vines within 1-5 years. No cure. CDFA coordination required. Area-wide management essential.', true),
      (3, 'Tuta absoluta Spread Alert', 'Tomato Leaf Miner', 'Gujarat, India', 'high', 'Tomato', 'Invasive pest continuing rapid spread across tomato-growing regions', 'Pheromone traps, IPM approach, avoid over-reliance on insecticides', 'Resistance to multiple insecticide classes already reported globally. IPM approach essential: pheromone traps (40/ha), Trichogramma releases, spinosad rotation.', true),
      (3, 'White Grub Damage Season', 'White Grubs', 'Maharashtra, India', 'medium', 'Sugarcane, Groundnut', 'Adult beetle emergence beginning with pre-monsoon rains', 'Light traps for adult beetles, soil treatment before planting', 'June beetle flight coincides with monsoon onset. Light traps at 1/acre reduce adult population. Soil application of chlorpyrifos or Metarhizium at planting provides larval control.', true),
      (1, 'Japanese Beetle Adult Emergence', 'Japanese Beetle', 'Eastern USA', 'medium', 'Corn, Soybean, Apple, Grape', 'Adult emergence beginning, feeding damage expected for 6-8 weeks', 'Bt milky disease for grubs, hand-pick adults on small plantings', 'Adults cause cosmetic damage to many plants but rarely economic except on silk clipping in corn. Trap crops of preferred species can concentrate beetles away from cash crops.', true),
      (2, 'Brown Marmorated Stink Bug Alert', 'Brown Marmorated Stink Bug', 'Mid-Atlantic, USA', 'high', 'Apple, Peach, Tomato, Pepper, Soybean', 'Population building in border rows of orchards and vegetable fields', 'Border sprays, trap crops, samurai wasp monitoring', 'BMSB feeds on 100+ host plants. Concentrate management on field/orchard borders where bugs first colonize. Samurai wasp (Trissolcus japonicus) establishing as biocontrol.', true),
      (3, 'Banana Bunchy Top Virus Alert', 'Banana Aphid (virus vector)', 'Southern India', 'critical', 'Banana', 'BBTV detected in new districts, spread by banana aphid', 'Use virus-free planting material, control aphid vectors', 'BBTV is devastating and incurable. Eradicate infected plants immediately including corm. 10m buffer zone. Only plant tissue-culture verified clean material. Imidacloprid for aphid control.', true)
    `);
    console.log('Pest alerts seeded');

    // 9. Disease History (15 items)
    await client.query(`
      INSERT INTO disease_history (user_id, crop_name, disease_name, occurrence_date, resolution_date, treatment_used, outcome, crop_loss_percentage, lessons_learned, ai_pattern_analysis) VALUES
      (1, 'Tomato', 'Early Blight', '2025-07-15', '2025-08-10', 'Chlorothalonil + crop rotation', 'Resolved', 15.0, 'Started fungicide too late. Need preventive applications.', 'Pattern: Early blight recurs annually in July. 3-year data shows correlation with >85% humidity periods. Preventive spray at first fruit set reduces loss from 15% to <5%.'),
      (1, 'Potato', 'Late Blight', '2025-08-20', '2025-09-15', 'Metalaxyl + vine kill', 'Managed', 35.0, 'Devastating when delayed. Must respond within 24 hours.', 'Late blight is your highest-risk disease. Weather-based forecasting (DSV model) could have given 5-day warning. Consider resistant varieties for 30% of acreage as insurance.'),
      (1, 'Wheat', 'Stripe Rust', '2025-05-10', '2025-06-01', 'Propiconazole at flag leaf', 'Resolved', 8.0, 'Variety susceptibility was the issue. Switch varieties.', 'Stripe rust correlates with cool spring temperatures and southerly wind events. Variety selection is #1 defense. Flag leaf timing spray was correct. Loss would be 25%+ without treatment.'),
      (1, 'Rice', 'Sheath Blight', '2025-09-01', '2025-10-05', 'Hexaconazole + drainage management', 'Managed', 20.0, 'Dense planting worsened the disease. Reduce seeding rate.', 'Sheath blight severity directly related to plant density and nitrogen rate. Reduce seeding rate by 20%. Split nitrogen into 3 applications instead of 2.'),
      (2, 'Soybean', 'Sudden Death Syndrome', '2025-07-01', '2025-08-15', 'Fluopyram seed treatment + drainage', 'Managed', 25.0, 'Low-lying wet areas worst. Install tile drainage.', 'SDS recurs in same field areas every year - mapping hot spots allows targeted management. Fluopyram seed treatment reduces loss by 10-15%. Drainage investment has 3-year ROI.'),
      (2, 'Apple', 'Apple Scab', '2025-05-20', '2025-07-10', 'Captan + myclobutanil spray program', 'Resolved', 12.0, 'Missed critical infection period during rain events.', 'Apple scab requires rain+temperature model (Mills table) for timing sprays. 2 missed spray windows in May caused primary infection. Investment in weather station justified.'),
      (2, 'Grape', 'Botrytis Bunch Rot', '2025-09-15', '2025-10-20', 'Fenhexamid + canopy management', 'Managed', 18.0, 'Tight clusters more susceptible. Consider cluster thinning.', 'Botrytis is chronic in this vineyard. Canopy management (leaf pulling, shoot positioning) reduced incidence by 40%. Combine with bloom-time fungicide for best results.'),
      (2, 'Cotton', 'Fusarium Wilt', '2025-06-15', '2025-08-30', 'Resistant variety + soil amendment', 'Managed', 22.0, 'Soil pathogen - need long-term management strategy.', 'Fusarium persists in soil indefinitely. Transition to resistant varieties over 3 years. Soil pH management (maintain 6.5-7.0) suppresses pathogen. Biocontrol with Trichoderma shows promise.'),
      (3, 'Coffee', 'Coffee Berry Disease', '2025-11-01', '2025-12-20', 'Copper spray + selective harvesting', 'Managed', 30.0, 'Devastating loss. Need resistant variety program.', 'CBD is your most economically damaging disease. 30% loss unacceptable. Resistant varieties (Ruiru 11, Batian) reduce loss to <5%. 5-year replanting program recommended.'),
      (3, 'Banana', 'Black Sigatoka', '2025-08-10', '2025-10-15', 'Propiconazole + leaf removal', 'Managed', 15.0, 'Continuous management required - no cure.', 'Black Sigatoka requires year-round management. Oil-based sprays in dry season, systemic fungicides in wet season. 12-leaf management system keeps disease below economic threshold.'),
      (3, 'Mango', 'Powdery Mildew', '2025-02-01', '2025-03-15', 'Sulfur + wettable sulfur spray', 'Resolved', 10.0, 'Apply sulfur before flowering for prevention.', 'Powdery mildew in mango correlates with cool dry nights during flowering. Sulfur spray at panicle emergence is most cost-effective timing. Two applications usually sufficient.'),
      (1, 'Strawberry', 'Anthracnose Crown Rot', '2025-06-20', '2025-07-30', 'Azoxystrobin + plant removal', 'Managed', 40.0, 'Used contaminated transplants. Verify nursery certification.', 'Catastrophic 40% loss traced to infected transplants. ALWAYS verify nursery plant health certification. Heat-treated transplants available. Azoxystrobin dip at planting as insurance.'),
      (1, 'Corn', 'Northern Corn Leaf Blight', '2025-08-05', '2025-09-10', 'Pyraclostrobin + metconazole at VT', 'Resolved', 10.0, 'Caught early enough to protect yield.', 'NCLB appearance correlates with susceptible hybrid and 3+ hours dew period. Fungicide at VT-R1 protected 90% of yield potential. Hybrid resistance rating should be key selection criteria.'),
      (2, 'Citrus', 'Citrus Black Spot', '2025-04-10', '2025-06-30', 'Copper + strobilurin program', 'Managed', 8.0, 'Cosmetic but affects marketability.', 'Black spot primarily a cosmetic issue but causes market rejection. 4-spray program from petal fall provides adequate control. Leaf litter management reduces inoculum for next season.'),
      (3, 'Cassava', 'Cassava Brown Streak', '2025-07-25', '2025-09-30', 'Roguing + clean planting material', 'Managed', 28.0, 'Devastating root necrosis. Early harvest salvaged some roots.', 'CBSD causes internal root necrosis invisible from outside. Regular leaf symptom surveys essential. Harvest symptomatic plants early (before 9 months) to salvage usable roots.')
    `);
    console.log('Disease history seeded');

    // 10. Community Reports (15 items)
    await client.query(`
      INSERT INTO community_reports (user_id, reporter_name, report_type, title, description, location, crop_affected, severity, verified, ai_verification) VALUES
      (1, 'Tom Henderson', 'Disease Outbreak', 'Early Blight Spreading in County', 'Multiple farms reporting early blight on tomatoes, worse than last year', 'Johnson County, Iowa', 'Tomato', 'high', true, 'Verified: Early blight reports consistent with weather conditions (warm + humid). Regional advisory confirmed by extension service. Recommend preventive fungicide in adjacent counties.'),
      (1, 'Maria Garcia', 'Pest Sighting', 'Japanese Beetle Swarm Near Airport', 'Massive Japanese beetle emergence defoliating ornamentals and crops', 'Cedar Rapids, Iowa', 'Corn, Soybean, Garden Crops', 'medium', true, 'Verified: Japanese beetle emergence timing normal for region. High population this year correlates with wet spring for grub development. Economic damage primarily cosmetic except corn silk.'),
      (1, 'Bob Wilson', 'Unusual Symptoms', 'Strange Yellowing in Wheat Field', 'Wheat showing unusual yellow streaking, not matching known diseases', 'Story County, Iowa', 'Wheat', 'medium', false, 'Unverified: Symptoms could be wheat streak mosaic virus (transmitted by wheat curl mite) or herbicide drift damage. Physical sample submission to diagnostic lab recommended.'),
      (2, 'Lisa Chen', 'Disease Outbreak', 'Sudden Oak Death Found in Nursery', 'Phytophthora ramorum detected in nursery stock, quarantine imposed', 'Sonoma County, California', 'Oak, Nursery Stock', 'critical', true, 'Verified: P. ramorum is a regulated pathogen. Quarantine appropriate. All nursery stock within 1 mile should be inspected. Report to CDFA. Do not move plant material from area.'),
      (2, 'Mike Johnson', 'Pest Sighting', 'European Grapevine Moth Trap Catch', 'First trap catch of EGVM in vineyard, previously not known in area', 'Napa Valley, California', 'Grape', 'critical', true, 'Verified: EGVM (Lobesia botrana) is a quarantine pest. Regulatory response required. Mating disruption highly effective. Alert all growers within 5-mile radius.'),
      (2, 'Sarah Thompson', 'Weather Damage', 'Hail Damage Assessment - Orchard', 'Golf ball sized hail damaged 60% of apple crop, open wounds visible', 'Wenatchee, WA', 'Apple', 'critical', true, 'Verified: Post-hail bacterial infection risk high. Immediate copper spray recommended within 24 hours. Document all damage with geo-tagged photos for crop insurance claim.'),
      (3, 'Raj Kumar', 'Disease Outbreak', 'Rice Blast Epidemic in District', 'Blast disease reaching epidemic levels across multiple villages', 'Thanjavur, Tamil Nadu', 'Rice', 'critical', true, 'Verified: Magnaporthe oryzae epidemic confirmed. Correlates with unusual cool cloudy period during tillering. Emergency fungicide distribution needed. Contact district agriculture officer.'),
      (3, 'Priya Sharma', 'Pest Sighting', 'Fall Armyworm First Detection', 'Larvae found in maize field, matches fall armyworm identification guide', 'Pune, Maharashtra', 'Maize', 'high', true, 'Verified: Spodoptera frugiperda confirmed by morphological features. Invasive pest spreading rapidly. Community awareness campaign needed. Pheromone trap network should be established.'),
      (3, 'Amit Patel', 'Market Alert', 'Fungicide Shortage in Local Markets', 'Copper fungicide stocks depleted across all agricultural shops in taluka', 'Anand, Gujarat', 'All Crops', 'high', true, 'Verified: Supply chain disruption likely due to monsoon demand spike. Alternative: Bordeaux mixture can be prepared from copper sulfate + lime. Contact cooperative for bulk ordering.'),
      (1, 'James Brown', 'New Disease', 'Tar Spot First Report in County', 'Black raised lesions on corn leaves matching tar spot descriptions', 'Jasper County, Iowa', 'Corn', 'high', true, 'Verified: Phyllachora maydis (tar spot) continues northward spread. First confirmed county record. Yield impact 10-30 bu/acre in severe cases. Fungicide at VT-R1 timing recommended.'),
      (2, 'Emma Davis', 'Beneficial Sighting', 'Monarch Butterfly Migration Through Farm', 'Large numbers of monarchs observed, requesting pesticide spray delay', 'Central Valley, CA', 'Various', 'low', true, 'Verified: Monarch migration route confirmed. Delay broad-spectrum insecticide applications 5-7 days where possible. Plant milkweed buffer strips. Great opportunity for beneficial insect conservation.'),
      (2, 'David Lee', 'Pest Sighting', 'Spotted Lanternfly Egg Masses', 'Egg masses found on farm equipment arriving from Pennsylvania', 'Sacramento, CA', 'Grape, Stone Fruits', 'critical', true, 'Verified: CRITICAL biosecurity concern. Spotted lanternfly (Lycorma delicatula) not established in CA. Destroy all egg masses. Report to CDFA immediately. Quarantine equipment.'),
      (3, 'Suresh Reddy', 'Success Story', 'IPM Program Reduced Pesticide 60%', 'Village cooperative IPM program showing dramatic pesticide reduction', 'Warangal, Telangana', 'Cotton', 'low', true, 'Verified: Community IPM success story. Key components: pheromone traps, Trichogramma releases, NSKE sprays, border crops. Replicable model for neighboring villages.'),
      (1, 'Nancy White', 'Unusual Symptoms', 'Dicamba Drift Damage on Soybeans', 'Non-dicamba-tolerant soybeans showing cupping and epinasty symptoms', 'Des Moines County, Iowa', 'Soybean', 'high', true, 'Verified: Classic dicamba drift symptoms. Document with photos, note date/time, wind records. Contact state pesticide bureau. File complaint within 60 days for investigation.'),
      (3, 'Deepak Singh', 'Infrastructure', 'Cold Storage Facility Needed for District', 'Post-harvest losses reaching 30% for vegetables due to no cold storage', 'Nashik, Maharashtra', 'Vegetables', 'high', true, 'Verified: Post-harvest loss is a critical infrastructure gap. Government subsidies available under MIDH scheme. Solar-powered cold rooms suitable for remote areas. Cost: approx. ₹15-20 lakhs.')
    `);
    console.log('Community reports seeded');

    // 11. Expert Consultations (15 items)
    await client.query(`
      INSERT INTO expert_consultations (user_id, expert_name, specialization, question, crop_name, response, consultation_type, rating, status, ai_preliminary_response) VALUES
      (1, 'Dr. Sarah Mitchell', 'Plant Pathology', 'What is the best resistant tomato variety for early blight in Zone 5?', 'Tomato', 'Mountain Merit and Defiant PHR show excellent EB resistance. Both are determinate. For indeterminate, try Juliet (cherry) or Iron Lady.', 'variety_selection', 5, 'answered', 'Based on regional trial data, Mountain Merit (F1), Defiant PHR, and Iron Lady show strong Alternaria resistance. Mountain Merit also has late blight resistance.'),
      (1, 'Dr. James Rodriguez', 'Entomology', 'Are neonicotinoid seed treatments still justified for corn in my area?', 'Corn', 'Depends on your rootworm pressure and planting conditions. If soil temps >12°C at planting and you rotate crops, seed treatment ROI is negative.', 'pest_management', 4, 'answered', 'Meta-analysis shows neonicotinoid seed treatments provide inconsistent yield benefit in rotated corn. Consider using only where rootworm pressure is documented.'),
      (1, 'Dr. Emily Watson', 'Soil Science', 'My pH dropped from 6.8 to 5.9 in two years. What happened?', 'Corn', 'Likely cause: high ammonium-N fertilizer without liming. Each lb of anhydrous ammonia acidifies soil requiring 1.8 lb lime equivalent to neutralize.', 'soil_health', 5, 'answered', 'Rapid pH decline most commonly caused by nitrogen fertilizer acidification. Ammonium-based fertilizers release H+ during nitrification. Lime at 2 tons/acre, switch to UAN for less acidification.'),
      (2, 'Dr. Michael Chang', 'Pomology', 'My apple trees had a heavy crop last year and nothing this year. How do I fix biennial bearing?', 'Apple', 'Chemical thinning at petal fall is key. Use 6-BA + carbaryl at 10mm fruit size. Target 1 fruit per cluster, 6 inches between clusters.', 'crop_management', 5, 'answered', 'Biennial bearing is common in unthinned apple trees. Chemical thinning (NAA or 6-BA based) at petal fall breaks the cycle. Manual thinning as backup to achieve 40-60 leaves per fruit.'),
      (2, 'Dr. Ana Martinez', 'Viticulture', 'How do I manage smoke taint risk in my wine grapes?', 'Grape', 'Rapid harvest of affected blocks, separate vinification, activated carbon fining can reduce smoke phenols by 60%. Test free and bound volatile phenols.', 'quality_management', 4, 'answered', 'Smoke taint compounds (guaiacol, 4-methylguaiacol) bind to grape sugars. Free volatile phenols detectable by GC-MS. Activated carbon fining, early harvest, and sacrificing affected blocks may be necessary.'),
      (2, 'Dr. Robert Kim', 'Irrigation Science', 'What is the optimal deficit irrigation strategy for wine grapes?', 'Grape', 'Regulated Deficit Irrigation: irrigate at 100% ET until veraison, then reduce to 50% ET. Target midday leaf water potential of -1.2 to -1.4 MPa.', 'water_management', 5, 'answered', 'RDI for premium wine grapes: maintain adequate water pre-veraison for berry cell division. Post-veraison deficit concentrates flavors. Monitor with pressure chamber. Stem water potential more reliable than leaf.'),
      (3, 'Dr. Anita Desai', 'Tropical Agriculture', 'What is the best intercropping system for my coconut plantation?', 'Coconut', 'Coconut + cocoa is ideal for your rainfall. Below 25-year palms: cocoa gives best returns. Also consider black pepper on coconut trunks + nutmeg.', 'farm_planning', 5, 'answered', 'Multi-tier intercropping maximizes coconut plantation returns. Recommended: Coconut (top) + Cocoa (middle) + Pineapple/Ginger (ground). Adds 40-60% to plantation income with minimal competition.'),
      (3, 'Dr. Vijay Sharma', 'Plant Breeding', 'Should I switch from traditional cotton varieties to Bt cotton?', 'Cotton', 'Bt cotton provides bollworm protection but resistance management is critical. Plant 20% non-Bt refuge. Consider Bt2 (dual gene) varieties for durability.', 'variety_selection', 4, 'answered', 'Bt cotton significantly reduces bollworm damage and insecticide use. However, pink bollworm resistance to Cry1Ac is documented. Dual-gene (Cry1Ac + Cry2Ab) varieties recommended with proper refuge.'),
      (1, 'Dr. Patricia Hayes', 'Mycology', 'I found mushrooms growing in my corn field. Are they related to my disease problems?', 'Corn', 'Likely saprophytic fungi on decaying residue - not pathogenic. However, excessive residue can harbor Gibberella ear rot. Consider residue management.', 'diagnosis', 3, 'answered', 'Mushroom fruiting bodies in crop fields are usually saprophytic (decomposers) and not harmful. However, their presence indicates high organic residue. Monitor for mycotoxin-producing Fusarium in corn residue.'),
      (1, 'Dr. Thomas Grant', 'Agricultural Economics', 'Is precision agriculture worth the investment for my 500-acre farm?', 'Corn', 'At 500 acres, basic precision ag (auto-steer, yield monitor, VRA) typically pays back in 2-3 years. Start with yield mapping and VRA for lime and P.', 'farm_economics', 5, 'answered', 'Precision agriculture ROI analysis for 500-acre grain operation: GPS auto-steer saves 5-8% input overlap ($15-20/acre). Variable rate application saves $10-25/acre. Yield monitoring is foundational.'),
      (2, 'Dr. Karen Phillips', 'Food Safety', 'What are the FSMA requirements for my leafy greens operation?', 'Lettuce', 'FSMA Produce Safety Rule applies. Key: worker training, water quality testing, pre-harvest intervals for amendments, equipment sanitation, wildlife intrusion prevention.', 'compliance', 5, 'answered', 'FSMA Produce Safety Rule checklist: 1) Water quality testing (generic E. coli), 2) Biological soil amendments timing, 3) Worker hygiene training, 4) Equipment/tool sanitation, 5) Animal intrusion prevention.'),
      (2, 'Dr. David Morrison', 'Climate Science', 'How should I adapt my crop rotation for increasing drought frequency?', 'Various', 'Diversify with drought-tolerant crops (sorghum, millet). Build soil organic matter aggressively. Consider cover crop cocktails for water infiltration.', 'climate_adaptation', 4, 'answered', 'Climate adaptation strategy: 1) Soil health building increases water holding capacity (1% OM increase = 20,000 gal/acre), 2) Drought-tolerant varieties, 3) Cover crop cocktails, 4) Reduced tillage.'),
      (3, 'Dr. Lakshmi Nair', 'Organic Farming', 'How do I transition from conventional to organic banana production?', 'Banana', '3-year transition period required for certification. Start with soil building: composting, green manure cover crops. Biocontrol for Sigatoka: Trichoderma + botanical extracts.', 'organic_transition', 5, 'answered', 'Organic banana transition plan: Year 1-3 (transition): build soil biology, establish biocontrol programs, develop compost supply chain. Key challenges: Sigatoka management and nematode control without chemicals.'),
      (3, 'Dr. Rajan Menon', 'Post-Harvest', 'How can I reduce post-harvest losses in my mango export business?', 'Mango', 'Hot water treatment (52°C/5 min) for anthracnose. Modified atmosphere packaging. Cold chain maintenance at 13°C. Expect to reduce losses from 30% to under 10%.', 'post_harvest', 5, 'answered', 'Mango post-harvest protocol: 1) Harvest at mature-green stage, 2) Hot water treatment 52°C/5min, 3) Cool to 13°C within 6hrs, 4) Modified atmosphere (5% O2, 5% CO2), 5) Ethylene management.'),
      (1, 'Dr. Helen Foster', 'Weed Science', 'How do I manage herbicide-resistant waterhemp in my soybean fields?', 'Soybean', 'Waterhemp populations in Iowa commonly resist 4+ herbicide sites. Diversify: pre-emergence residuals (Authority + Dual), post with Liberty Link system, cover crops.', 'weed_management', 5, 'answered', 'Herbicide-resistant waterhemp management requires multiple effective sites of action: PRE (sulfentrazone + metolachlor) + POST (glufosinate in LL system). Cover crops reduce emergence 50-70%. Zero tolerance for seed production.')
    `);
    console.log('Expert consultations seeded');

    // 12. Marketplace Items (15 items)
    await client.query(`
      INSERT INTO marketplace_items (user_id, item_name, category, description, price, currency, seller_name, seller_location, availability, rating, ai_product_review) VALUES
      (1, 'Chlorothalonil 720 SC', 'Fungicide', 'Broad-spectrum contact fungicide for disease prevention. 2.5L bottle.', 45.99, 'USD', 'AgriSupply Co.', 'Des Moines, Iowa', 'in_stock', 4.5, 'Excellent broad-spectrum protectant fungicide. Best for preventive applications. Does not move systemically - thorough coverage essential. Cost-effective for large acreage. Mix with spreader-sticker.'),
      (1, 'Spinosad Organic Insecticide', 'Insecticide', 'OMRI-listed natural insecticide derived from soil bacterium. 1 quart.', 38.50, 'USD', 'Organic Farm Supply', 'Iowa City, Iowa', 'in_stock', 4.8, 'Top-rated organic insecticide. Excellent against caterpillars, thrips, and leafminers. Apply in evening to protect pollinators. Breaks down in sunlight within 1-2 days. Minimal impact on beneficials.'),
      (1, 'Copper Hydroxide 77WP', 'Fungicide', 'Copper-based bactericide/fungicide for organic and conventional use. 5 lb bag.', 32.00, 'USD', 'CropChem Direct', 'Omaha, Nebraska', 'in_stock', 4.2, 'Essential copper product for bacterial disease management. Acceptable in organic production. Apply with oil for better adherence. Avoid high-rate applications near harvest - residue concerns.'),
      (2, 'Pheromone Trap Kit - Codling Moth', 'Monitoring', 'Complete trap kit with 6 pheromone lures and delta traps. Season supply.', 89.99, 'USD', 'Pest Solutions Inc.', 'Yakima, WA', 'in_stock', 4.7, 'Essential monitoring tool for apple/pear orchards. Delta trap design easy to service. Lures effective for 4-6 weeks. Place 2 traps per 5-acre block. Action threshold: 5 moths per trap per week.'),
      (2, 'Drip Irrigation Starter Kit', 'Irrigation', 'Complete drip system for 1 acre: mainline, laterals, emitters, filter, timer.', 599.00, 'USD', 'IrrigationPro', 'Fresno, CA', 'in_stock', 4.6, 'Well-designed starter kit for small farm. 2 GPH emitters suitable for most vegetable crops. Includes 200-mesh filter essential for clog prevention. Upgrade timer to smart controller for best results.'),
      (2, 'Soil Test Kit - Professional', 'Testing', 'Complete soil analysis kit: pH, N, P, K, organic matter. 25 sample capacity.', 149.99, 'USD', 'SoilTech Labs', 'Sacramento, CA', 'in_stock', 4.4, 'Professional-grade testing comparable to lab results for pH and macronutrients. Good for frequent monitoring between lab tests. Calibrate against lab results initially. Worth the investment for serious growers.'),
      (3, 'Trichoderma Bio-Fungicide', 'Biological', 'Trichoderma harzianum concentrated powder for soil and foliar application. 1 kg.', 28.00, 'USD', 'BioAgri Solutions', 'Bangalore, India', 'in_stock', 4.3, 'Excellent biocontrol agent for soil-borne diseases (Fusarium, Pythium, Rhizoctonia). Apply to soil before planting. Also effective as seed treatment. Store in cool dry place - live organism.'),
      (3, 'Solar-Powered Pest Light Trap', 'Monitoring', 'Autonomous solar light trap for nocturnal pest monitoring and mass trapping.', 75.00, 'USD', 'AgTech India', 'Hyderabad, India', 'in_stock', 4.1, 'Solar operation makes this ideal for remote fields without electricity. Effective for moth monitoring (bollworm, armyworm). Place at crop canopy height. Clean collection tray weekly. Battery lasts 3+ seasons.'),
      (1, 'Bt Kurstaki Concentrate', 'Biological', 'Bacillus thuringiensis var. kurstaki for caterpillar control. 1 pint concentrate.', 24.99, 'USD', 'Natural Pest Control', 'Portland, OR', 'in_stock', 4.6, 'The gold standard organic caterpillar control. Mix fresh for each application. Apply in evening for best results - UV degrades Bt. Most effective on young larvae. Safe for all beneficial insects.'),
      (1, 'Weather Station - Farm Pro', 'Technology', 'Connected weather station with temp, humidity, rainfall, wind, leaf wetness sensors.', 449.00, 'USD', 'WeatherTech Ag', 'Minneapolis, MN', 'in_stock', 4.8, 'Outstanding investment for disease prediction. Leaf wetness sensor enables accurate spray timing. WiFi connectivity for remote monitoring. Disease forecast models available as subscription add-on.'),
      (2, 'Grafting Tool Kit Professional', 'Equipment', 'Complete grafting set: omega cutter, grafting tape, sealant, knives, tutorial DVD.', 65.00, 'USD', 'Orchard Tools Co.', 'Wenatchee, WA', 'in_stock', 4.5, 'Omega grafting tool produces consistent grafts with 90%+ take rate. Suitable for apple, grape, and stone fruit. Spring grafting preferred. Include rootstock and scion selection guide.'),
      (2, 'Neem Oil Cold-Pressed', 'Organic', 'Pure cold-pressed neem oil for insect and fungal disease control. 1 gallon.', 42.00, 'USD', 'Pure Organics', 'San Diego, CA', 'in_stock', 4.3, 'Multi-purpose organic product: insecticide (azadirachtin), fungicide, and miticide. Cold-pressed retains more active ingredient than extracted. Emulsify with soap before mixing. Do not apply in direct sun or >30°C.'),
      (3, 'Vermicompost Premium Grade', 'Fertilizer', 'Worm castings from organic waste. Rich in microorganisms and humic acids. 50 kg bag.', 15.00, 'USD', 'WormFarm India', 'Coimbatore, India', 'in_stock', 4.7, 'Exceptional quality vermicompost. NPK approximately 2-1-1 plus rich microbiome. Apply 2-5 tons/acre as soil amendment. Also excellent for potting mix (20-30% by volume). Disease-suppressive properties documented.'),
      (3, 'Knapsack Sprayer 16L', 'Equipment', 'Manual backpack sprayer with brass nozzles, adjustable pressure. Heavy duty.', 35.00, 'USD', 'FarmEquip', 'Mumbai, India', 'in_stock', 4.0, 'Reliable manual sprayer suitable for smallholder farms. Brass nozzles resist corrosion. Clean thoroughly after each use - residue buildup causes clogging. Consider cone nozzle for fungicides, flat fan for herbicides.'),
      (1, 'Cover Crop Seed Mix - Premium', 'Seeds', 'Custom blend: crimson clover, winter rye, radish, hairy vetch. 50 lb bag covers 1 acre.', 89.00, 'USD', 'Green Cover Seed', 'Bladen, NE', 'in_stock', 4.9, 'Outstanding diverse cover crop mix. Crimson clover fixes N (80-100 lb/acre), radish breaks compaction, rye builds organic matter, vetch provides spring N. Plant by Sept 15 for best establishment. Terminate 2 weeks before cash crop.')
    `);
    console.log('Marketplace items seeded');

    // 13. Farm Management (15 items)
    await client.query(`
      INSERT INTO farm_management (user_id, farm_name, field_name, crop_name, area_size, area_unit, planting_date, expected_harvest, irrigation_type, status, notes, ai_management_tips) VALUES
      (1, 'Green Valley Farm', 'North Field A', 'Tomato', 5.0, 'acres', '2026-05-01', '2026-08-15', 'Drip', 'active', 'Determinate variety Mountain Merit, plastic mulch', 'Optimal management: stake/cage at planting, prune to 4 main stems, side-dress calcium nitrate at first fruit. Expected yield: 25 tons/acre with proper management.'),
      (1, 'Green Valley Farm', 'West Block B', 'Wheat', 80.0, 'acres', '2025-10-01', '2026-07-10', 'Rainfed', 'active', 'Winter wheat, SY Monument variety', 'Spring nitrogen application critical at greenup. Split: 60 lb N at Feekes 3, 40 lb N at Feekes 6. Scout for stripe rust at flag leaf. Target yield: 70 bu/acre.'),
      (1, 'Green Valley Farm', 'South Field 1', 'Corn', 120.0, 'acres', '2026-04-15', '2026-10-01', 'Center Pivot', 'planned', 'Pioneer P1185AM, 34,000 pop', 'Pre-plant: anhydrous ammonia 150 lb N/acre. Starter: 10-34-0 in furrow. Side-dress option at V6 based on tissue test. Monitor ECB and rootworm pressure.'),
      (1, 'Green Valley Farm', 'East Plot', 'Potato', 15.0, 'acres', '2026-04-20', '2026-09-01', 'Sprinkler', 'planned', 'Russet Burbank for processing market', 'Seed piece treatment essential. Plant 12-inch spacing in 36-inch rows. Hill at emergence and again at 8 inches. Late blight scouting starts at row closure. Target: 400 cwt/acre.'),
      (1, 'Green Valley Farm', 'Greenhouse 1', 'Strawberry', 0.5, 'acres', '2026-08-15', '2027-06-30', 'Drip', 'planned', 'Day-neutral Albion variety, high tunnel', 'Substrate culture in coco coir for disease avoidance. Fertigation EC 1.2-1.6. Bumble bee hives for pollination. Target: 1.5 lb/plant over season. Runner management critical.'),
      (2, 'Sunrise Acres', 'Orchard East', 'Apple', 25.0, 'acres', '2020-03-15', '2026-09-15', 'Micro-sprinkler', 'active', 'Honeycrisp on M.9 rootstock, 6th leaf', 'Honeycrisp requires special attention: calcium sprays (6-8 applications), fruit thinning for size, careful nitrogen management. Bitter pit prevention is #1 priority for pack-out.'),
      (2, 'Sunrise Acres', 'Vineyard A', 'Grape', 12.0, 'acres', '2018-04-01', '2026-09-20', 'Drip', 'active', 'Cabernet Sauvignon on 110R rootstock', 'Deficit irrigation post-veraison for wine quality. Canopy management: shoot thin to 4-5 shoots per foot of row. Leaf pulling on morning sun side at fruit set. Target: 4 tons/acre.'),
      (2, 'Sunrise Acres', 'Block C', 'Soybean', 60.0, 'acres', '2026-05-10', '2026-10-15', 'Rainfed', 'planned', 'Asgrow AG36X6 variety, Liberty Link', 'Inoculate with Bradyrhizobium if field has not grown soybeans in 3+ years. Plant 140,000 seeds/acre in 15-inch rows. Liberty herbicide program for waterhemp management.'),
      (2, 'Sunrise Acres', 'Cotton Zone 2', 'Cotton', 40.0, 'acres', '2026-05-01', '2026-11-15', 'Furrow', 'planned', 'Deltapine DP 2038 B3XF', 'Plant when soil temp >65°F at 4 inches for 3 consecutive days. PGR (mepiquat) at matchhead square. PIX program through bloom. Target: 3.5 bales/acre.'),
      (3, 'Patel Organics', 'Plantation Sector 1', 'Coffee', 10.0, 'acres', '2022-06-15', '2026-11-01', 'Drip', 'active', 'Arabica, shade-grown with Grevillea', 'Shade management: 40-50% canopy cover optimal. Compost application 5 kg/tree annually. Selective harvesting for quality premium. Target: 1,200 kg clean coffee/acre.'),
      (3, 'Patel Organics', 'Plantation B', 'Banana', 8.0, 'acres', '2025-06-01', '2026-06-01', 'Basin', 'active', 'Grand Naine tissue culture plants', 'Desuckering monthly to maintain mother-follower-peeper system. Bunch cover with blue polythene bag at shooting. Prop support when bunch heavy. Target: 30 kg/bunch average.'),
      (3, 'Patel Organics', 'Grove East', 'Mango', 15.0, 'acres', '2015-07-01', '2026-05-15', 'Drip', 'active', 'Alphonso variety, 11-year trees', 'Paclobutrazol for regular flowering (10g/m canopy diameter). Pre-bloom fungicide for powdery mildew. Fruit bagging reduces fly damage. Target: 10 tons/acre for mature trees.'),
      (3, 'Patel Organics', 'Plot 5', 'Cassava', 5.0, 'acres', '2026-04-20', '2027-02-01', 'Rainfed', 'planned', 'Local improved variety, mound planting', 'Stake selection from 8-12 month plants. Mound planting for easy harvest. Intercrop with legume for first 3 months. Weed management critical first 90 days. Target: 25 tons fresh root/acre.'),
      (1, 'Green Valley Farm', 'Paddy Field 2', 'Rice', 20.0, 'acres', '2026-06-15', '2026-11-01', 'Flood', 'planned', 'Jasmine 85 variety, puddled transplanting', 'SRI method: single seedling, 25x25 cm spacing, alternate wetting-drying. Reduces water use 30% and increases yield 15%. Mechanical weeder at 15 and 30 DAT.'),
      (2, 'Sunrise Acres', 'Orange Grove', 'Citrus', 20.0, 'acres', '2019-03-15', '2026-12-01', 'Micro-sprinkler', 'active', 'Valencia orange, 7th year grove', 'HLB prevention: systemic psyllid treatment 3x/year. Foliar nutrition program to maintain tree health. Fruit quality peaks with 2-3 months between color break and harvest. Target: 400 boxes/acre.')
    `);
    console.log('Farm management seeded');

    // 14. Knowledge Base (15 items)
    await client.query(`
      INSERT INTO knowledge_base (title, category, content, crop_type, disease_or_pest, region, difficulty_level, tags, views, ai_enhanced_content) VALUES
      ('Understanding Early Blight in Tomatoes', 'Disease Guide', 'Early blight (Alternaria solani) is one of the most common tomato diseases worldwide. It typically starts on lower, older leaves and progresses upward.', 'Tomato', 'Early Blight', 'Global', 'beginner', 'tomato,early-blight,fungal,alternaria', 1250, 'Complete early blight management: 1) Resistant varieties (Mountain Merit, Defiant), 2) Mulching prevents soil splash, 3) Lower leaf pruning, 4) Fungicide rotation: chlorothalonil + mancozeb, 5) 3-year rotation away from Solanaceae.'),
      ('Integrated Pest Management Fundamentals', 'IPM Guide', 'IPM is a science-based approach that combines biological, cultural, physical, and chemical tools to minimize pest damage while reducing risks to people and the environment.', 'All Crops', 'General', 'Global', 'beginner', 'ipm,pest-management,biological-control,sustainable', 2340, 'IPM hierarchy: 1) Prevention (resistant varieties, clean seed, rotation), 2) Monitoring (scouting, traps, thresholds), 3) Cultural control (timing, spacing, sanitation), 4) Biological control, 5) Chemical control (last resort, targeted).'),
      ('Soil Health: The Foundation of Disease Resistance', 'Soil Science', 'Healthy soil is the first line of defense against crop diseases. Soil biodiversity suppresses pathogens, improves nutrient availability, and enhances plant immunity.', 'All Crops', 'Soil-borne Diseases', 'Global', 'intermediate', 'soil-health,disease-suppression,organic-matter,microbiome', 1890, 'Soil disease suppression mechanisms: 1) Competition for resources, 2) Antibiosis (natural antibiotics), 3) Induced systemic resistance in plants. Build suppressive soils: add diverse organic matter, minimize tillage, diverse rotations.'),
      ('Fall Armyworm: A Global Threat', 'Pest Guide', 'Spodoptera frugiperda has spread from the Americas to Africa and Asia, threatening food security for millions of smallholder farmers.', 'Corn, Rice, Sorghum', 'Fall Armyworm', 'Global', 'intermediate', 'fall-armyworm,invasive,corn,spodoptera', 3100, 'FAW management for smallholders: 1) Early detection (scout whorl stage weekly), 2) Push-pull technology (Napier border, Desmodium intercrop), 3) Bt spray for organic, 4) Selective insecticides at threshold, 5) Natural enemies: Trichogramma, earwigs, ants.'),
      ('Precision Agriculture for Smallholder Farms', 'Technology', 'Precision agriculture is not just for large farms. Smartphone-based tools are making precision techniques accessible to smallholders worldwide.', 'All Crops', 'General', 'Developing Regions', 'beginner', 'precision-ag,smartphone,technology,smallholder', 1670, 'Smartphone precision ag tools for smallholders: 1) Plantix app for disease ID, 2) AgroStar for advisory, 3) Weather apps with disease models, 4) Digital record keeping, 5) Market price apps. Total cost: just a smartphone.'),
      ('Biological Control: Natural Enemies of Crop Pests', 'Biological Control', 'Conservation and augmentation of natural enemies can reduce pest populations by 50-90% without synthetic pesticides.', 'All Crops', 'General', 'Global', 'intermediate', 'biological-control,natural-enemies,parasitoids,predators', 2100, 'Key biocontrol agents: 1) Trichogramma wasps (egg parasitoids), 2) Chrysoperla lacewings (aphid predators), 3) Phytoseiulus persimilis (spider mite predator), 4) Beauveria bassiana (entomopathogenic fungus), 5) Trichoderma (soil biocontrol).'),
      ('Climate Change and Emerging Plant Diseases', 'Climate Science', 'Climate change is altering the distribution and severity of plant diseases, creating new challenges for farmers worldwide.', 'All Crops', 'Various', 'Global', 'advanced', 'climate-change,emerging-diseases,adaptation,risk', 2450, 'Climate impacts on plant disease: 1) Range expansion of tropical pathogens northward, 2) Increased severity of heat-loving pathogens, 3) Changed phenology mismatching natural controls, 4) New pathogen-host interactions. Adaptation: diverse varieties, monitoring networks.'),
      ('Water Management for Disease Prevention', 'Irrigation', 'Irrigation management directly impacts disease development. Overhead irrigation promotes foliar diseases while drip irrigation minimizes leaf wetness.', 'All Crops', 'Fungal Diseases', 'Global', 'beginner', 'irrigation,water-management,leaf-wetness,disease-prevention', 1430, 'Irrigation and disease link: 1) Drip irrigation reduces foliar disease 40-60%, 2) Morning irrigation allows leaf drying, 3) Avoid overhead irrigation during humid periods, 4) Deficit irrigation can reduce Botrytis, 5) Proper drainage prevents root diseases.'),
      ('Organic Disease Management Strategies', 'Organic Farming', 'Organic farming relies on prevention, biodiversity, and approved natural products to manage crop diseases without synthetic fungicides.', 'All Crops', 'Various', 'Global', 'intermediate', 'organic,disease-management,copper,biocontrol,prevention', 1980, 'Organic disease management toolbox: 1) Resistant varieties (most important), 2) Crop rotation (minimum 3-year), 3) Copper products (limit accumulation), 4) Sulfur (powdery mildew), 5) Bacillus-based biofungicides, 6) Compost tea, 7) Sanitation.'),
      ('Understanding Pesticide Resistance', 'Resistance Management', 'Pesticide resistance is an evolutionary response where pest populations survive previously lethal doses. It threatens the sustainability of chemical control.', 'All Crops', 'General', 'Global', 'advanced', 'resistance,fungicide,insecticide,management,FRAC,IRAC', 2670, 'Resistance management strategy: 1) Rotate modes of action (FRAC/IRAC groups), 2) Tank mix different groups, 3) Use full recommended rate, 4) Integrate non-chemical tactics, 5) Monitor for efficacy decline. Never use same MOA more than 2 consecutive applications.'),
      ('Post-Harvest Disease Management', 'Post-Harvest', 'Up to 40% of crop production in developing countries is lost after harvest, largely due to diseases and improper storage conditions.', 'Fruits, Vegetables', 'Post-harvest Pathogens', 'Developing Regions', 'intermediate', 'post-harvest,storage,cold-chain,food-loss,developing', 1560, 'Reduce post-harvest disease: 1) Harvest at correct maturity, 2) Minimize physical damage, 3) Hot water treatment (crop-specific protocols), 4) Rapid cooling, 5) Proper storage temperature and humidity, 6) Modified atmosphere, 7) Biological agents (Candida oleophila).'),
      ('Mycotoxins in Grain: Detection and Prevention', 'Food Safety', 'Mycotoxins produced by Fusarium, Aspergillus, and Penicillium species contaminate 25% of world grain crops, posing serious health risks.', 'Grain Crops', 'Mycotoxin Producers', 'Global', 'advanced', 'mycotoxins,aflatoxin,fusarium,grain-safety,food-safety', 2230, 'Mycotoxin prevention chain: 1) Resistant varieties, 2) Harvest timing (avoid over-maturity), 3) Rapid drying to <14% moisture, 4) Clean storage facilities, 5) HACCP monitoring, 6) Biocontrol (Aflasafe for aflatoxin). Testing: ELISA for screening, LC-MS/MS for confirmation.'),
      ('Drone Technology in Crop Disease Detection', 'Technology', 'Multispectral and hyperspectral drone imagery can detect crop diseases 7-14 days before visible symptoms appear, enabling early intervention.', 'All Crops', 'Various', 'Global', 'advanced', 'drone,remote-sensing,NDVI,multispectral,early-detection', 3450, 'Drone disease detection: 1) NDVI for general stress, 2) Red-edge index for chlorophyll status, 3) Thermal for water stress, 4) AI-powered image classification for specific diseases. Cost: $5-15/acre/flight. ROI positive at 50+ acres. Regulatory: check FAA Part 107 requirements.'),
      ('Seed Treatment: First Line of Defense', 'Crop Protection', 'Modern seed treatments protect seeds and seedlings from soil-borne diseases, insects, and nematodes during the critical establishment phase.', 'All Crops', 'Soil-borne Pathogens', 'Global', 'beginner', 'seed-treatment,seedling-disease,pythium,rhizoctonia,establishment', 1340, 'Seed treatment categories: 1) Fungicide (metalaxyl + fludioxonil for Pythium + Rhizoctonia), 2) Insecticide (clothianidin for wireworm), 3) Nematicide (abamectin), 4) Biological (Trichoderma, Bacillus). Seed treatment ROI: typically 5-10:1 return on investment.'),
      ('Community-Based Plant Health Clinics', 'Extension', 'Plant health clinics bring diagnostic expertise directly to farming communities, enabling rapid disease identification and treatment recommendations.', 'All Crops', 'General', 'Developing Regions', 'beginner', 'plant-clinic,extension,diagnosis,community,smallholder', 890, 'Plant clinic model: 1) Weekly clinic at market/community center, 2) Trained plant doctor examines samples, 3) Diagnosis and treatment recommendation on-site, 4) Data collection for surveillance, 5) Referral to lab for difficult cases. Plantwise model active in 30+ countries.')
    `);
    console.log('Knowledge base seeded');

    // 15. Analytics Data (15 items)
    await client.query(`
      INSERT INTO analytics_data (user_id, metric_name, metric_value, metric_unit, category, period, crop_name, comparison_value, trend, ai_insight) VALUES
      (1, 'Disease Detection Accuracy', 92.5, 'percent', 'AI Performance', '2026-Q1', 'All Crops', 88.3, 'improving', 'AI detection accuracy improved 4.2% over last quarter. Tomato and citrus diseases have highest accuracy (95%+). Rice diseases need more training data for improvement.'),
      (1, 'Crop Yield - Corn', 195.0, 'bushels/acre', 'Yield', '2025', 'Corn', 182.0, 'improving', 'Yield improvement of 7.1% attributed to precision nitrogen management and timely fungicide application. Target for 2026: 205 bu/acre with VRA technology.'),
      (1, 'Pesticide Reduction', 35.0, 'percent', 'Sustainability', '2025', 'All Crops', 20.0, 'improving', 'IPM program reduced pesticide use 35% while maintaining yield. Key driver: biological control adoption and threshold-based spraying. Target: 50% reduction by 2027.'),
      (1, 'Water Use Efficiency', 78.5, 'percent', 'Resource Use', '2026-Q1', 'All Crops', 65.0, 'improving', 'Drip irrigation and soil moisture monitoring improved water use efficiency 13.5 percentage points. Saves approximately 2 acre-inches per acre per season.'),
      (2, 'Crop Loss Prevention', 850000.0, 'dollars', 'Economic', '2025', 'All Crops', 620000.0, 'improving', 'Early disease detection prevented estimated $850K in crop losses. ROI on detection system: 12:1. Biggest savings: early apple scab detection saved $180K in Honeycrisp crop.'),
      (2, 'Organic Premium Revenue', 125000.0, 'dollars', 'Revenue', '2025', 'Grape', 95000.0, 'improving', 'Organic wine grape premium increasing. 31.6% revenue increase year-over-year. Market trend supports continued organic transition for remaining 5 acres.'),
      (2, 'Pest Alert Response Time', 4.2, 'hours', 'Operations', '2026-Q1', 'All Crops', 18.5, 'improving', 'Alert response time reduced from 18.5 hours to 4.2 hours with mobile notification system. Faster response correlates with 30% less crop damage from pest outbreaks.'),
      (2, 'Soil Health Index', 7.8, 'index', 'Soil', '2026-Q1', 'All Crops', 6.2, 'improving', 'Soil health improved 25.8% through cover cropping and reduced tillage. Biological activity indicators (respiration, active carbon) showing strongest improvement.'),
      (3, 'Smallholder Adoption Rate', 340.0, 'farmers', 'Community', '2026-Q1', 'All Crops', 180.0, 'improving', 'Platform adoption nearly doubled. Mobile-first design critical for success. Top features used: disease detection (89%), weather alerts (76%), marketplace (65%).'),
      (3, 'Export Quality Compliance', 96.0, 'percent', 'Quality', '2025', 'Mango', 82.0, 'improving', 'Mango export quality improved from 82% to 96% compliance. Key factors: post-harvest treatment protocol, cold chain management, and pre-harvest disease control.'),
      (3, 'Farm Income Increase', 45.0, 'percent', 'Economic', '2025', 'All Crops', 28.0, 'improving', 'Average farm income increased 45% for platform users vs 28% regional average. AI recommendations for treatment timing and market timing are primary value drivers.'),
      (1, 'Carbon Sequestration', 2.5, 'tons CO2/acre', 'Sustainability', '2025', 'All Crops', 1.8, 'improving', 'Cover cropping and no-till increased carbon sequestration 38.9%. Potential carbon credit revenue: $15-25/ton. Cumulative storage: 250 tons CO2 across farm.'),
      (1, 'Disease Forecast Accuracy', 88.0, 'percent', 'AI Performance', '2026-Q1', 'All Crops', 75.0, 'improving', 'Weather-based disease forecasting accuracy reached 88%. Late blight model most accurate (94%). Improvement driven by local weather station data integration.'),
      (2, 'Labor Efficiency', 22.0, 'percent', 'Operations', '2025', 'All Crops', 0.0, 'improving', 'Automation and AI-guided scouting reduced labor hours by 22%. Drone scouting replaces 60% of manual field walks. Targeted spraying reduces application time 35%.'),
      (3, 'Post-Harvest Loss Reduction', 12.0, 'percent', 'Sustainability', '2025', 'Vegetables', 32.0, 'improving', 'Post-harvest losses reduced from 32% to 12% through cold chain implementation and market linkage. Impact: 20% more product reaching market, equivalent to farming 20% more land.')
    `);
    console.log('Analytics data seeded');

    console.log('\\n✅ All seed data inserted successfully!');
  } catch (err) {
    console.error('Seed error:', err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
