export const featureConfig = [
  {
    name: 'Disease Detection',
    shortName: 'Diseases',
    icon: '🔬',
    path: '/diseases',
    apiPath: '/disease-detections',
    description: 'AI-powered crop disease detection and diagnosis',
    color: '#ef4444',
    columns: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'disease_name', label: 'Disease' },
      { key: 'confidence', label: 'Confidence', suffix: '%' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { key: 'disease_name', label: 'Disease Name', type: 'text', required: true },
      { key: 'confidence', label: 'Confidence (%)', type: 'number' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'symptoms', label: 'Symptoms', type: 'textarea' },
      { key: 'affected_area', label: 'Affected Area', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['detected', 'treating', 'resolved'] },
    ],
    detailFields: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'disease_name', label: 'Disease' },
      { key: 'confidence', label: 'Confidence', suffix: '%' },
      { key: 'severity', label: 'Severity' },
      { key: 'symptoms', label: 'Symptoms' },
      { key: 'affected_area', label: 'Affected Area' },
      { key: 'status', label: 'Status' },
      { key: 'ai_diagnosis', label: 'AI Diagnosis', isAI: true },
    ],
    aiPromptFields: ['crop_name', 'disease_name', 'symptoms', 'severity'],
  },
  {
    name: 'Pest Identification',
    shortName: 'Pests',
    icon: '🐛',
    path: '/pests',
    apiPath: '/pest-identifications',
    description: 'Identify and manage crop pests with AI',
    color: '#f97316',
    columns: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'pest_name', label: 'Pest' },
      { key: 'pest_type', label: 'Type' },
      { key: 'damage_level', label: 'Damage', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { key: 'pest_name', label: 'Pest Name', type: 'text', required: true },
      { key: 'pest_type', label: 'Pest Type', type: 'select', options: ['Insect', 'Arachnid', 'Nematode', 'Rodent', 'Mollusk', 'Bird'] },
      { key: 'confidence', label: 'Confidence (%)', type: 'number' },
      { key: 'damage_level', label: 'Damage Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'recommended_action', label: 'Recommended Action', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['identified', 'treating', 'resolved'] },
    ],
    detailFields: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'pest_name', label: 'Pest' },
      { key: 'pest_type', label: 'Type' },
      { key: 'confidence', label: 'Confidence', suffix: '%' },
      { key: 'damage_level', label: 'Damage Level' },
      { key: 'description', label: 'Description' },
      { key: 'recommended_action', label: 'Recommended Action' },
      { key: 'status', label: 'Status' },
      { key: 'ai_analysis', label: 'AI Analysis', isAI: true },
    ],
    aiPromptFields: ['crop_name', 'pest_name', 'pest_type', 'damage_level', 'description'],
  },
  {
    name: 'Crop Health',
    shortName: 'Health',
    icon: '🌱',
    path: '/crop-health',
    apiPath: '/crop-health',
    description: 'Monitor and track crop health metrics',
    color: '#16a34a',
    columns: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'field_name', label: 'Field' },
      { key: 'health_score', label: 'Score', suffix: '/100' },
      { key: 'growth_stage', label: 'Growth Stage' },
      { key: 'water_stress', label: 'Water Stress', badge: true },
    ],
    fields: [
      { key: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'health_score', label: 'Health Score (0-100)', type: 'number' },
      { key: 'growth_stage', label: 'Growth Stage', type: 'text' },
      { key: 'ndvi_value', label: 'NDVI Value', type: 'number' },
      { key: 'chlorophyll_level', label: 'Chlorophyll Level', type: 'select', options: ['low', 'below_normal', 'normal', 'optimal'] },
      { key: 'water_stress', label: 'Water Stress', type: 'select', options: ['none', 'mild', 'moderate', 'high'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    detailFields: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'field_name', label: 'Field' },
      { key: 'health_score', label: 'Health Score' },
      { key: 'growth_stage', label: 'Growth Stage' },
      { key: 'ndvi_value', label: 'NDVI Value' },
      { key: 'chlorophyll_level', label: 'Chlorophyll Level' },
      { key: 'water_stress', label: 'Water Stress' },
      { key: 'notes', label: 'Notes' },
      { key: 'ai_assessment', label: 'AI Assessment', isAI: true },
    ],
    aiPromptFields: ['crop_name', 'field_name', 'health_score', 'growth_stage', 'ndvi_value', 'chlorophyll_level', 'water_stress'],
  },
  {
    name: 'Treatments',
    shortName: 'Treatments',
    icon: '💊',
    path: '/treatments',
    apiPath: '/treatments',
    description: 'AI-recommended treatment plans',
    color: '#06b6d4',
    columns: [
      { key: 'disease_or_pest', label: 'Disease/Pest' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'treatment_type', label: 'Type' },
      { key: 'treatment_name', label: 'Treatment' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'disease_or_pest', label: 'Disease or Pest', type: 'text', required: true },
      { key: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { key: 'treatment_type', label: 'Treatment Type', type: 'select', options: ['Fungicide', 'Insecticide', 'Biological', 'Cultural', 'IPM', 'Bactericide', 'Pheromone'] },
      { key: 'treatment_name', label: 'Treatment Name', type: 'text' },
      { key: 'dosage', label: 'Dosage', type: 'text' },
      { key: 'application_method', label: 'Application Method', type: 'textarea' },
      { key: 'frequency', label: 'Frequency', type: 'text' },
      { key: 'precautions', label: 'Precautions', type: 'textarea' },
      { key: 'organic_alternative', label: 'Organic Alternative', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['recommended', 'active', 'completed'] },
    ],
    detailFields: [
      { key: 'disease_or_pest', label: 'Disease/Pest' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'treatment_type', label: 'Type' },
      { key: 'treatment_name', label: 'Treatment' },
      { key: 'dosage', label: 'Dosage' },
      { key: 'application_method', label: 'Application Method' },
      { key: 'frequency', label: 'Frequency' },
      { key: 'precautions', label: 'Precautions' },
      { key: 'organic_alternative', label: 'Organic Alternative' },
      { key: 'effectiveness_rating', label: 'Effectiveness Rating', suffix: '/100' },
      { key: 'status', label: 'Status' },
      { key: 'ai_recommendation', label: 'AI Recommendation', isAI: true },
    ],
    aiPromptFields: ['disease_or_pest', 'crop_name', 'treatment_type', 'treatment_name'],
  },
  {
    name: 'Weather Risks',
    shortName: 'Weather',
    icon: '🌦️',
    path: '/weather-risks',
    apiPath: '/weather-risks',
    description: 'Weather-based disease risk assessment',
    color: '#3b82f6',
    columns: [
      { key: 'location', label: 'Location' },
      { key: 'risk_type', label: 'Risk Type' },
      { key: 'risk_level', label: 'Risk Level', badge: true },
      { key: 'temperature', label: 'Temp', suffix: '°C' },
      { key: 'humidity', label: 'Humidity', suffix: '%' },
    ],
    fields: [
      { key: 'location', label: 'Location', type: 'text', required: true },
      { key: 'risk_type', label: 'Risk Type', type: 'text' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'temperature', label: 'Temperature (°C)', type: 'number' },
      { key: 'humidity', label: 'Humidity (%)', type: 'number' },
      { key: 'rainfall', label: 'Rainfall (mm)', type: 'number' },
      { key: 'wind_speed', label: 'Wind Speed (km/h)', type: 'number' },
      { key: 'forecast_summary', label: 'Forecast Summary', type: 'textarea' },
      { key: 'disease_risk_factors', label: 'Disease Risk Factors', type: 'textarea' },
    ],
    detailFields: [
      { key: 'location', label: 'Location' },
      { key: 'risk_type', label: 'Risk Type' },
      { key: 'risk_level', label: 'Risk Level' },
      { key: 'temperature', label: 'Temperature', suffix: '°C' },
      { key: 'humidity', label: 'Humidity', suffix: '%' },
      { key: 'rainfall', label: 'Rainfall', suffix: 'mm' },
      { key: 'wind_speed', label: 'Wind Speed', suffix: 'km/h' },
      { key: 'forecast_summary', label: 'Forecast' },
      { key: 'disease_risk_factors', label: 'Risk Factors' },
      { key: 'ai_risk_analysis', label: 'AI Risk Analysis', isAI: true },
    ],
    aiPromptFields: ['location', 'risk_type', 'temperature', 'humidity', 'rainfall'],
  },
  {
    name: 'Soil Analysis',
    shortName: 'Soil',
    icon: '🧪',
    path: '/soil-analysis',
    apiPath: '/soil-analyses',
    description: 'Soil health testing and recommendations',
    color: '#92400e',
    columns: [
      { key: 'field_name', label: 'Field' },
      { key: 'soil_type', label: 'Soil Type' },
      { key: 'ph_level', label: 'pH' },
      { key: 'organic_matter', label: 'Organic Matter', suffix: '%' },
      { key: 'moisture_content', label: 'Moisture', suffix: '%' },
    ],
    fields: [
      { key: 'field_name', label: 'Field Name', type: 'text', required: true },
      { key: 'soil_type', label: 'Soil Type', type: 'text' },
      { key: 'ph_level', label: 'pH Level', type: 'number' },
      { key: 'nitrogen_level', label: 'Nitrogen (ppm)', type: 'number' },
      { key: 'phosphorus_level', label: 'Phosphorus (ppm)', type: 'number' },
      { key: 'potassium_level', label: 'Potassium (ppm)', type: 'number' },
      { key: 'organic_matter', label: 'Organic Matter (%)', type: 'number' },
      { key: 'moisture_content', label: 'Moisture Content (%)', type: 'number' },
      { key: 'recommendations', label: 'Recommendations', type: 'textarea' },
    ],
    detailFields: [
      { key: 'field_name', label: 'Field' },
      { key: 'soil_type', label: 'Soil Type' },
      { key: 'ph_level', label: 'pH Level' },
      { key: 'nitrogen_level', label: 'Nitrogen', suffix: ' ppm' },
      { key: 'phosphorus_level', label: 'Phosphorus', suffix: ' ppm' },
      { key: 'potassium_level', label: 'Potassium', suffix: ' ppm' },
      { key: 'organic_matter', label: 'Organic Matter', suffix: '%' },
      { key: 'moisture_content', label: 'Moisture', suffix: '%' },
      { key: 'recommendations', label: 'Recommendations' },
      { key: 'ai_analysis', label: 'AI Analysis', isAI: true },
    ],
    aiPromptFields: ['field_name', 'soil_type', 'ph_level', 'nitrogen_level', 'phosphorus_level', 'potassium_level', 'organic_matter'],
  },
  {
    name: 'Crop Calendar',
    shortName: 'Calendar',
    icon: '📅',
    path: '/crop-calendar',
    apiPath: '/crop-calendar',
    description: 'Plan and schedule farming activities',
    color: '#7c3aed',
    columns: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'activity', label: 'Activity' },
      { key: 'scheduled_date', label: 'Date' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { key: 'activity', label: 'Activity', type: 'text', required: true },
      { key: 'scheduled_date', label: 'Scheduled Date', type: 'date' },
      { key: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['planned', 'in_progress', 'completed'] },
    ],
    detailFields: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'activity', label: 'Activity' },
      { key: 'scheduled_date', label: 'Scheduled Date' },
      { key: 'season', label: 'Season' },
      { key: 'priority', label: 'Priority' },
      { key: 'notes', label: 'Notes' },
      { key: 'status', label: 'Status' },
      { key: 'ai_suggestion', label: 'AI Suggestion', isAI: true },
    ],
    aiPromptFields: ['crop_name', 'activity', 'season', 'scheduled_date'],
  },
  {
    name: 'Pest Alerts',
    shortName: 'Alerts',
    icon: '🚨',
    path: '/pest-alerts',
    apiPath: '/pest-alerts',
    description: 'Regional pest alert notifications',
    color: '#dc2626',
    columns: [
      { key: 'alert_title', label: 'Alert' },
      { key: 'pest_name', label: 'Pest' },
      { key: 'region', label: 'Region' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'is_active', label: 'Active', boolean: true },
    ],
    fields: [
      { key: 'alert_title', label: 'Alert Title', type: 'text', required: true },
      { key: 'pest_name', label: 'Pest Name', type: 'text' },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'affected_crops', label: 'Affected Crops', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'prevention_tips', label: 'Prevention Tips', type: 'textarea' },
      { key: 'is_active', label: 'Is Active', type: 'select', options: ['true', 'false'] },
    ],
    detailFields: [
      { key: 'alert_title', label: 'Alert Title' },
      { key: 'pest_name', label: 'Pest' },
      { key: 'region', label: 'Region' },
      { key: 'severity', label: 'Severity' },
      { key: 'affected_crops', label: 'Affected Crops' },
      { key: 'description', label: 'Description' },
      { key: 'prevention_tips', label: 'Prevention Tips' },
      { key: 'is_active', label: 'Active' },
      { key: 'ai_alert_analysis', label: 'AI Analysis', isAI: true },
    ],
    aiPromptFields: ['alert_title', 'pest_name', 'region', 'severity', 'affected_crops'],
  },
  {
    name: 'Disease History',
    shortName: 'History',
    icon: '📋',
    path: '/disease-history',
    apiPath: '/disease-history',
    description: 'Track disease occurrence patterns',
    color: '#6b7280',
    columns: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'disease_name', label: 'Disease' },
      { key: 'occurrence_date', label: 'Date' },
      { key: 'outcome', label: 'Outcome' },
      { key: 'crop_loss_percentage', label: 'Loss', suffix: '%' },
    ],
    fields: [
      { key: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { key: 'disease_name', label: 'Disease Name', type: 'text', required: true },
      { key: 'occurrence_date', label: 'Occurrence Date', type: 'date' },
      { key: 'resolution_date', label: 'Resolution Date', type: 'date' },
      { key: 'treatment_used', label: 'Treatment Used', type: 'textarea' },
      { key: 'outcome', label: 'Outcome', type: 'select', options: ['Resolved', 'Managed', 'Ongoing', 'Failed'] },
      { key: 'crop_loss_percentage', label: 'Crop Loss (%)', type: 'number' },
      { key: 'lessons_learned', label: 'Lessons Learned', type: 'textarea' },
    ],
    detailFields: [
      { key: 'crop_name', label: 'Crop' },
      { key: 'disease_name', label: 'Disease' },
      { key: 'occurrence_date', label: 'Occurrence Date' },
      { key: 'resolution_date', label: 'Resolution Date' },
      { key: 'treatment_used', label: 'Treatment Used' },
      { key: 'outcome', label: 'Outcome' },
      { key: 'crop_loss_percentage', label: 'Crop Loss', suffix: '%' },
      { key: 'lessons_learned', label: 'Lessons Learned' },
      { key: 'ai_pattern_analysis', label: 'AI Pattern Analysis', isAI: true },
    ],
    aiPromptFields: ['crop_name', 'disease_name', 'treatment_used', 'outcome', 'crop_loss_percentage'],
  },
  {
    name: 'Community Reports',
    shortName: 'Community',
    icon: '👥',
    path: '/community',
    apiPath: '/community-reports',
    description: 'Community disease and pest reports',
    color: '#0891b2',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'report_type', label: 'Type' },
      { key: 'location', label: 'Location' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'verified', label: 'Verified', boolean: true },
    ],
    fields: [
      { key: 'reporter_name', label: 'Reporter Name', type: 'text' },
      { key: 'report_type', label: 'Report Type', type: 'select', options: ['Disease Outbreak', 'Pest Sighting', 'Weather Damage', 'Unusual Symptoms', 'Market Alert', 'New Disease', 'Success Story', 'Beneficial Sighting', 'Infrastructure'] },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'crop_affected', label: 'Crop Affected', type: 'text' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
    ],
    detailFields: [
      { key: 'reporter_name', label: 'Reporter' },
      { key: 'report_type', label: 'Type' },
      { key: 'title', label: 'Title' },
      { key: 'description', label: 'Description' },
      { key: 'location', label: 'Location' },
      { key: 'crop_affected', label: 'Crop Affected' },
      { key: 'severity', label: 'Severity' },
      { key: 'verified', label: 'Verified' },
      { key: 'ai_verification', label: 'AI Verification', isAI: true },
    ],
    aiPromptFields: ['report_type', 'title', 'description', 'location', 'crop_affected', 'severity'],
  },
  {
    name: 'Expert Consultations',
    shortName: 'Experts',
    icon: '🎓',
    path: '/consultations',
    apiPath: '/expert-consultations',
    description: 'Get expert advice on crop issues',
    color: '#6d28d9',
    columns: [
      { key: 'expert_name', label: 'Expert' },
      { key: 'specialization', label: 'Specialization' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'rating', label: 'Rating', suffix: '/5' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'expert_name', label: 'Expert Name', type: 'text' },
      { key: 'specialization', label: 'Specialization', type: 'text' },
      { key: 'question', label: 'Question', type: 'textarea', required: true },
      { key: 'crop_name', label: 'Crop Name', type: 'text' },
      { key: 'consultation_type', label: 'Consultation Type', type: 'select', options: ['variety_selection', 'pest_management', 'soil_health', 'crop_management', 'quality_management', 'water_management', 'farm_planning', 'organic_transition', 'diagnosis', 'farm_economics', 'compliance', 'climate_adaptation', 'post_harvest', 'weed_management'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'answered', 'closed'] },
    ],
    detailFields: [
      { key: 'expert_name', label: 'Expert' },
      { key: 'specialization', label: 'Specialization' },
      { key: 'question', label: 'Question' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'response', label: 'Expert Response' },
      { key: 'consultation_type', label: 'Type' },
      { key: 'rating', label: 'Rating', suffix: '/5' },
      { key: 'status', label: 'Status' },
      { key: 'ai_preliminary_response', label: 'AI Preliminary Response', isAI: true },
    ],
    aiPromptFields: ['question', 'crop_name', 'specialization'],
  },
  {
    name: 'Marketplace',
    shortName: 'Market',
    icon: '🛒',
    path: '/marketplace',
    apiPath: '/marketplace',
    description: 'Agricultural products and supplies',
    color: '#059669',
    columns: [
      { key: 'item_name', label: 'Product' },
      { key: 'category', label: 'Category' },
      { key: 'price', label: 'Price', prefix: '$' },
      { key: 'availability', label: 'Availability', badge: true },
      { key: 'rating', label: 'Rating', suffix: '/5' },
    ],
    fields: [
      { key: 'item_name', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Fungicide', 'Insecticide', 'Biological', 'Organic', 'Monitoring', 'Irrigation', 'Testing', 'Technology', 'Equipment', 'Seeds', 'Fertilizer'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'price', label: 'Price ($)', type: 'number' },
      { key: 'seller_name', label: 'Seller Name', type: 'text' },
      { key: 'seller_location', label: 'Seller Location', type: 'text' },
      { key: 'availability', label: 'Availability', type: 'select', options: ['in_stock', 'limited', 'out_of_stock', 'pre_order'] },
    ],
    detailFields: [
      { key: 'item_name', label: 'Product' },
      { key: 'category', label: 'Category' },
      { key: 'description', label: 'Description' },
      { key: 'price', label: 'Price', prefix: '$' },
      { key: 'seller_name', label: 'Seller' },
      { key: 'seller_location', label: 'Location' },
      { key: 'availability', label: 'Availability' },
      { key: 'rating', label: 'Rating', suffix: '/5' },
      { key: 'ai_product_review', label: 'AI Product Review', isAI: true },
    ],
    aiPromptFields: ['item_name', 'category', 'description', 'price'],
  },
  {
    name: 'Farm Management',
    shortName: 'Farms',
    icon: '🏡',
    path: '/farm-management',
    apiPath: '/farm-management',
    description: 'Manage farm fields and crops',
    color: '#b45309',
    columns: [
      { key: 'farm_name', label: 'Farm' },
      { key: 'field_name', label: 'Field' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'area_size', label: 'Area' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'farm_name', label: 'Farm Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'crop_name', label: 'Crop Name', type: 'text' },
      { key: 'area_size', label: 'Area Size', type: 'number' },
      { key: 'area_unit', label: 'Area Unit', type: 'select', options: ['acres', 'hectares', 'sq_meters'] },
      { key: 'planting_date', label: 'Planting Date', type: 'date' },
      { key: 'expected_harvest', label: 'Expected Harvest', type: 'date' },
      { key: 'irrigation_type', label: 'Irrigation Type', type: 'select', options: ['Drip', 'Sprinkler', 'Flood', 'Center Pivot', 'Furrow', 'Micro-sprinkler', 'Basin', 'Rainfed'] },
      { key: 'status', label: 'Status', type: 'select', options: ['planned', 'active', 'harvested', 'fallow'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    detailFields: [
      { key: 'farm_name', label: 'Farm' },
      { key: 'field_name', label: 'Field' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'area_size', label: 'Area Size' },
      { key: 'area_unit', label: 'Unit' },
      { key: 'planting_date', label: 'Planting Date' },
      { key: 'expected_harvest', label: 'Expected Harvest' },
      { key: 'irrigation_type', label: 'Irrigation' },
      { key: 'status', label: 'Status' },
      { key: 'notes', label: 'Notes' },
      { key: 'ai_management_tips', label: 'AI Management Tips', isAI: true },
    ],
    aiPromptFields: ['farm_name', 'field_name', 'crop_name', 'area_size', 'irrigation_type'],
  },
  {
    name: 'Knowledge Base',
    shortName: 'Knowledge',
    icon: '📚',
    path: '/knowledge-base',
    apiPath: '/knowledge-base',
    description: 'Agricultural knowledge library',
    color: '#4338ca',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'crop_type', label: 'Crop Type' },
      { key: 'difficulty_level', label: 'Level', badge: true },
      { key: 'views', label: 'Views' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'crop_type', label: 'Crop Type', type: 'text' },
      { key: 'disease_or_pest', label: 'Disease/Pest', type: 'text' },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'difficulty_level', label: 'Difficulty Level', type: 'select', options: ['beginner', 'intermediate', 'advanced'] },
      { key: 'tags', label: 'Tags (comma-separated)', type: 'text' },
    ],
    detailFields: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'content', label: 'Content' },
      { key: 'crop_type', label: 'Crop Type' },
      { key: 'disease_or_pest', label: 'Disease/Pest' },
      { key: 'region', label: 'Region' },
      { key: 'difficulty_level', label: 'Level' },
      { key: 'tags', label: 'Tags' },
      { key: 'views', label: 'Views' },
      { key: 'ai_enhanced_content', label: 'AI Enhanced Content', isAI: true },
    ],
    aiPromptFields: ['title', 'category', 'content', 'crop_type'],
  },
  {
    name: 'Analytics',
    shortName: 'Analytics',
    icon: '📈',
    path: '/analytics',
    apiPath: '/analytics',
    description: 'Farm performance analytics and insights',
    color: '#be185d',
    columns: [
      { key: 'metric_name', label: 'Metric' },
      { key: 'metric_value', label: 'Value' },
      { key: 'category', label: 'Category' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'trend', label: 'Trend', badge: true },
    ],
    fields: [
      { key: 'metric_name', label: 'Metric Name', type: 'text', required: true },
      { key: 'metric_value', label: 'Value', type: 'number' },
      { key: 'metric_unit', label: 'Unit', type: 'text' },
      { key: 'category', label: 'Category', type: 'select', options: ['AI Performance', 'Yield', 'Sustainability', 'Resource Use', 'Economic', 'Revenue', 'Operations', 'Soil', 'Community', 'Quality'] },
      { key: 'period', label: 'Period', type: 'text' },
      { key: 'crop_name', label: 'Crop Name', type: 'text' },
      { key: 'comparison_value', label: 'Previous Value', type: 'number' },
      { key: 'trend', label: 'Trend', type: 'select', options: ['improving', 'stable', 'declining'] },
    ],
    detailFields: [
      { key: 'metric_name', label: 'Metric' },
      { key: 'metric_value', label: 'Current Value' },
      { key: 'metric_unit', label: 'Unit' },
      { key: 'category', label: 'Category' },
      { key: 'period', label: 'Period' },
      { key: 'crop_name', label: 'Crop' },
      { key: 'comparison_value', label: 'Previous Value' },
      { key: 'trend', label: 'Trend' },
      { key: 'ai_insight', label: 'AI Insight', isAI: true },
    ],
    aiPromptFields: ['metric_name', 'metric_value', 'metric_unit', 'category', 'crop_name', 'trend'],
  },
];
